municipalities_per_state = {
    'AGUASCALIENTES': {
        '1.0': 'AGUASCALIENTES',
        '2.0': 'ASIENTOS',
        '3.0': 'CALVILLO',
        '4.0': 'COSIO',
        '5.0': 'JESUS MARIA',
        '6.0': 'PABELLON DE ARTEAGA',
        '7.0': 'RINCON DE ROMOS',
        '8.0': 'SAN JOSE DE GRACIA',
        '9.0': 'TEPEZALA',
        '10.0': 'EL LLANO',
        '11.0': 'SAN FRANCISCO DE LOS ROMO'
    },
    'BAJA CALIFORNIA': {
        '1.0': 'ENSENADA',
        '2.0': 'MEXICALI',
        '3.0': 'TECATE',
        '4.0': 'TIJUANA',
        '5.0': 'PLAYAS DE ROSARITO'
    },
    'BAJA CALIFORNIA SUR': {
        '1.0': 'COMONDU',
        '2.0': 'LA PAZ',
        '3.0': 'LOS CABOS',
        '4.0': 'LORETO',
        '5.0': 'MULEGE'
    },
    'CAMPECHE': {
        '1.0': 'CALKINÍ',
        '2.0': 'CAMPECHE',
        '3.0': 'CARMEN',
        '4.0': 'CHAMPOTÓN',
        '5.0': 'HECELCHAKÁN',
        '6.0': 'HOPELCHÉN',
        '7.0': 'PALIZADA',
        '8.0': 'TENABO',
        '9.0': 'ESCÁRCEGA',
        '10.0': 'CALAKMUL',
        '11.0': 'CANDELARIA'
    },
    'COAHUILA DE ZARAGOZA': {
        '1.0': 'ABASOLO',
        '2.0': 'ACUÑA',
        '3.0': 'ALLENDE',
        '4.0': 'ARTEAGA',
        '5.0': 'CANDELA',
        '6.0': 'CASTAÑOS',
        '7.0': 'CUATRO CIÉNEGAS',
        '8.0': 'ESCOBEDO',
        '9.0': 'FRANCISCO I. MADERO',
        '10.0': 'FRONTERA',
        '11.0': 'GENERAL CEPEDA',
        '12.0': 'GUERRERO',
        '13.0': 'HIDALGO',
        '14.0': 'JIMÉNEZ',
        '15.0': 'JUÁREZ',
        '16.0': 'LAMADRID',
        '17.0': 'MATAMOROS',
        '18.0': 'MONCLOVA',
        '19.0': 'MORELOS',
        '20.0': 'MUZQUIZ',
        '21.0': 'NADADORES',
        '22.0': 'NAVA',
        '23.0': 'OCAMPO',
        '24.0': 'PARRAS',
        '25.0': 'PIEDRAS NEGRAS',
        '26.0': 'PROGRESO',
        '27.0': 'RAMOS ARIZPE',
        '28.0': 'SABINAS',
        '29.0': 'SACRAMENTO',
        '30.0': 'SALTILLO',
        '31.0': 'SAN BUENAVENTURA',
        '32.0': 'SAN JUAN DE SABINAS',
        '33.0': 'SAN PEDRO',
        '34.0': 'SIERRA MOJADA',
        '35.0': 'TORREÓN',
        '36.0': 'VIESCA',
        '37.0': 'VILLA UNIÓN',
        '38.0': 'ZARAGOZA'
    },

    'COLIMA': {
        '1.0': 'ARMERÍA',
        '2.0': 'COLIMA',
        '3.0': 'COMALA',
        '4.0': 'COQUIMATLÁN',
        '5.0': 'CUAUHTÉMOC',
        '6.0': 'IXTLAHUACÁN',
        '7.0': 'MANZANILLO',
        '8.0': 'MINATITLÁN',
        '9.0': 'TECOMÁN',
        '10.0': 'VILLA DE ÁLVAREZ'
    },
    'CHIAPAS': {
        '1.0': 'ACACOYAGUA',
        '2.0': 'ACALA',
        '3.0': 'ACAPETAHUA',
        '4.0': 'ALTAMIRANO',
        '5.0': 'AMATÁN',
        '6.0': 'AMATENANGO DE LA FRONTERA',
        '7.0': 'AMATENANGO DEL VALLE',
        '8.0': 'ANGEL ALBINO CORZO',
        '9.0': 'ARRIAGA',
        '10.0': 'BEJUCAL DE OCAMPO',
        '11.0': 'BELLA VISTA',
        '12.0': 'BERRIOZÁBAL',
        '13.0': 'BOCHIL',
        '14.0': 'EL BOSQUE',
        '15.0': 'CACAHOATÁN',
        '16.0': 'CATAZAJÁ',
        '17.0': 'CINTALAPA',
        '18.0': 'COAPILLA',
        '19.0': 'COMITÁN DE DOMÍNGUEZ',
        '20.0': 'LA CONCORDIA',
        '21.0': 'COPAINALÁ',
        '22.0': 'CHALCHIHUITÁN',
        '23.0': 'CHAMULA',
        '24.0': 'CHANAL',
        '25.0': 'CHAPULTENANGO',
        '26.0': 'CHENALHÓ',
        '27.0': 'CHIAPA DE CORZO',
        '28.0': 'CHIAPILLA',
        '29.0': 'CHICOASÉN',
        '30.0': 'CHICOMUSELO',
        '31.0': 'CHILÓN',
        '32.0': 'ESCUINTLA',
        '33.0': 'FRANCISCO LEÓN',
        '34.0': 'FRONTERA COMALAPA',
        '35.0': 'FRONTERA HIDALGO',
        '36.0': 'LA GRANDEZA',
        '37.0': 'HUEHUETÁN',
        '38.0': 'HUIXTÁN',
        '39.0': 'HUITIUPÁN',
        '40.0': 'HUIXTLA',
        '41.0': 'LA INDEPENDENCIA',
        '42.0': 'IXHUATÁN',
        '43.0': 'IXTACOMITÁN',
        '44.0': 'IXTAPA',
        '45.0': 'IXTAPANGAJOYA',
        '46.0': 'JIQUIPILAS',
        '47.0': 'JITOTOL',
        '48.0': 'JUÁREZ',
        '49.0': 'LARRÁINZAR',
        '50.0': 'LA LIBERTAD',
        '51.0': 'MAPASTEPEC',
        '52.0': 'LAS MARGARITAS',
        '53.0': 'MAZAPA DE MADERO',
        '54.0': 'MAZATÁN',
        '55.0': 'METAPA',
        '56.0': 'MITONTIC',
        '57.0': 'MOTOZINTLA',
        '58.0': 'NICOLÁS RUÍZ',
        '59.0': 'OCOSINGO',
        '60.0': 'OCOTEPEC',
        '61.0': 'OCOZOCOAUTLA DE ESPINOSA',
        '62.0': 'OSTUACÁN',
        '63.0': 'OSUMACINTA',
        '64.0': 'OXCHUC',
        '65.0': 'PALENQUE',
        '66.0': 'PANTELHÓ',
        '67.0': 'PANTEPEC',
        '68.0': 'PICHUCALCO',
        '69.0': 'PIJIJIAPAN',
        '70.0': 'EL PORVENIR',
        '71.0': 'VILLA COMALTITLÁN',
        '72.0': 'PUEBLO NUEVO SOLISTAHUACÁN',
        '73.0': 'RAYÓN',
        '74.0': 'REFORMA',
        '75.0': 'LAS ROSAS',
        '76.0': 'SABANILLA',
        '77.0': 'SALTO DE AGUA',
        '78.0': 'SAN CRISTÓBAL DE LAS CASAS',
        '79.0': 'SAN FERNANDO',
        '80.0': 'SILTEPEC',
        '81.0': 'SIMOJOVEL',
        '82.0': 'SITALÁ',
        '83.0': 'SOCOLTENANGO',
        '84.0': 'SOLOSUCHIAPA',
        '85.0': 'SOYALÓ',
        '86.0': 'SUCHIAPA',
        '87.0': 'SUCHIATE',
        '88.0': 'SUNUAPA',
        '89.0': 'TAPACHULA',
        '90.0': 'TAPALAPA',
        '91.0': 'TAPILULA',
        '92.0': 'TECPATÁN',
        '93.0': 'TENEJAPA',
        '94.0': 'TEOPISCA',
        '96.0': 'TILA',
        '97.0': 'TONALÁ',
        '98.0': 'TOTOLAPA',
        '99.0': 'LA TRINITARIA',
        '100.0': 'TUMBALÁ',
        '101.0': 'TUXTLA GUTIÉRREZ',
        '102.0': 'TUXTLA CHICO',
        '103.0': 'TUZANTÁN',
        '104.0': 'TZIMOL',
        '105.0': 'UNIÓN JUÁREZ',
        '106.0': 'VENUSTIANO CARRANZA',
        '107.0': 'VILLA CORZO',
        '108.0': 'VILLAFLORES',
        '109.0': 'YAJALÓN',
        '110.0': 'SAN LUCAS',
        '111.0': 'ZINACANTÁN',
        '112.0': 'SAN JUAN CANCUC',
        '113.0': 'ALDAMA',
        '114.0': 'BENEMÉRITO DE LAS AMÉRICAS',
        '115.0': 'MARAVILLA TENEJAPA',
        '116.0': 'MARQUÉS DE COMILLAS',
        '117.0': 'MONTECRISTO DE GUERRERO',
        '118.0': 'SAN ANDRÉS DURAZNAL',
        '119.0': 'SANTIAGO EL PINAR',
        '120.0': 'CAPITÁN LUIS ÁNGEL VIDAL',
        '121.0': 'RINCÓN CHAMULA SAN PEDRO',
        '122.0': 'EL PARRAL',
        '123.0': 'EMILIANO ZAPATA',
        '124.0': 'MEZCALAPA'
    },
    'CHIHUAHUA': {
        '1.0': 'AHUMADA',
        '2.0': 'ALDAMA',
        '3.0': 'ALLENDE',
        '4.0': 'AQUILES SERDÁN',
        '5.0': 'ASCENSIÓN',
        '6.0': 'BACHÍNIVA',
        '7.0': 'BALLEZA',
        '8.0': 'BATOPILAS DE MANUEL GÓMEZ MORÍN',
        '9.0': 'BOCOYNA',
        '10.0': 'BUENAVENTURA',
        '11.0': 'CAMARGO',
        '12.0': 'CARICHÍ',
        '13.0': 'CASAS GRANDES',
        '14.0': 'CORONADO',
        '15.0': 'COYAME DEL SOTOL',
        '16.0': 'LA CRUZ',
        '17.0': 'CUAUHTÉMOC',
        '18.0': 'CUSIHUIRIACHI',
        '19.0': 'CHIHUAHUA',
        '20.0': 'CHÍNIPAS',
        '21.0': 'DELICIAS',
        '22.0': 'DR. BELISARIO DOMÍNGUEZ',
        '23.0': 'GALEANA',
        '24.0': 'SANTA ISABEL',
        '25.0': 'GÓMEZ FARÍAS',
        '26.0': 'GRAN MORELOS',
        '27.0': 'GUACHOCHI',
        '28.0': 'GUADALUPE',
        '29.0': 'GUADALUPE Y CALVO',
        '30.0': 'GUAZAPARES',
        '31.0': 'GUERRERO',
        '32.0': 'HIDALGO DEL PARRAL',
        '33.0': 'HUEJOTITÁN',
        '34.0': 'IGNACIO ZARAGOZA',
        '35.0': 'JANOS',
        '36.0': 'JIMÉNEZ',
        '37.0': 'JUÁREZ',
        '38.0': 'JULIMES',
        '39.0': 'LÓPEZ',
        '40.0': 'MADERA',
        '41.0': 'MAGUARICHI',
        '42.0': 'MANUEL BENAVIDES',
        '43.0': 'MATACHÍ',
        '44.0': 'MATAMOROS',
        '45.0': 'MEOQUI',
        '46.0': 'MORELOS',
        '47.0': 'MORIS',
        '48.0': 'NAMIQUIPA',
        '49.0': 'NONOAVA',
        '50.0': 'NUEVO CASAS GRANDES',
        '51.0': 'OCAMPO',
        '52.0': 'OJINAGA',
        '53.0': 'PRAXEDIS G. GUERRERO',
        '54.0': 'RIVA PALACIO',
        '55.0': 'ROSALES',
        '56.0': 'ROSARIO',
        '57.0': 'SAN FRANCISCO DE BORJA',
        '58.0': 'SAN FRANCISCO DE CONCHOS',
        '59.0': 'SAN FRANCISCO DEL ORO',
        '60.0': 'SANTA BÁRBARA',
        '61.0': 'SATEVÓ',
        '62.0': 'SAUCILLO',
        '63.0': 'TEMÓSACHIC',
        '64.0': 'EL TULE',
        '65.0': 'URIQUE',
        '66.0': 'URUACHI',
        '67.0': 'VALLE DE ZARAGOZA'
    },
    'CIUDAD DE MÉXICO': {
        '2.0': 'AZCAPOTZALCO',
        '3.0': 'COYOACÁN',
        '4.0': 'CUAJIMALPA DE MORELOS',
        '5.0': 'GUSTAVO A. MADERO',
        '6.0': 'IZTACALCO',
        '7.0': 'IZTAPALAPA',
        '8.0': 'LA MAGDALENA CONTRERAS',
        '9.0': 'MILPA ALTA',
        '10.0': 'ÁLVARO OBREGÓN',
        '11.0': 'TLÁHUAC',
        '12.0': 'TLALPAN',
        '13.0': 'XOCHIMILCO',
        '14.0': 'BENITO JUÁREZ',
        '15.0': 'CUAUHTÉMOC',
        '16.0': 'MIGUEL HIDALGO',
        '17.0': 'VENUSTIANO CARRANZA'
    },
    'DURANGO': {
        '1.0': 'CANATLÁN',
        '2.0': 'CÁNDELARIA',
        '3.0': 'CONETO DE COMONFORT',
        '4.0': 'CUENCAMÉ',
        '5.0': 'DURANGO',
        '6.0': 'GENERAL SIMÓN BOLÍVAR',
        '7.0': 'GÓMEZ PALACIO',
        '8.0': 'GUADALUPE VICTORIA',
        '9.0': 'GUANACEVÍ',
        '10.0': 'HIDALGO',
        '11.0': 'INDÉ',
        '12.0': 'LERDO',
        '13.0': 'MAPIMÍ',
        '14.0': 'MEZQUITAL',
        '15.0': 'NAZAS',
        '16.0': 'NOMBRE DE DIOS',
        '17.0': 'OCAMPO',
        '18.0': 'EL ORO',
        '19.0': 'OTÁEZ',
        '20.0': 'PÁNUCO DE CORONADO',
        '21.0': 'PEÑÓN BLANCO',
        '22.0': 'POANAS',
        '23.0': 'PUEBLO NUEVO',
        '24.0': 'RODEO',
        '25.0': 'SAN BERNARDO',
        '26.0': 'SAN DIMAS',
        '27.0': 'SAN JUAN DE GUADALUPE',
        '28.0': 'SAN JUAN DEL RÍO',
        '29.0': 'SAN LUIS DEL CORDERO',
        '30.0': 'SAN PEDRO DEL GALLO',
        '31.0': 'SANTA CLARA',
        '32.0': 'SANTIAGO PAPASQUIARO',
        '33.0': 'SÚCHIL',
        '34.0': 'TAMAZULA',
        '35.0': 'TEPEHUANES',
        '36.0': 'TLAHUALILO',
        '37.0': 'TOPIA',
        '38.0': 'VICENTE GUERRERO',
        '39.0': 'NUEVO IDEAL'
    },
    'GUANAJUATO': {
        '1.0': 'ABASOLO',
        '2.0': 'ACÁMBARO',
        '3.0': 'SAN MIGUEL DE ALLENDE',
        '4.0': 'APASEO EL ALTO',
        '5.0': 'APASEO EL GRANDE',
        '6.0': 'ATARJEA',
        '7.0': 'CELAYA',
        '8.0': 'MANUEL DOBLADO',
        '9.0': 'COMONFORT',
        '10.0': 'CORONEO',
        '11.0': 'CORTAZAR',
        '12.0': 'CUERÁMARO',
        '13.0': 'DOCTOR MORA',
        '14.0': 'DOLORES HIDALGO',
        '15.0': 'GUANAJUATO',
        '16.0': 'HUANÍMARO',
        '17.0': 'IRAPUATO',
        '18.0': 'JARAL DEL PROGRESO',
        '19.0': 'JERECUARO',
        '20.0': 'LEÓN',
        '21.0': 'MOROLEÓN',
        '22.0': 'OCAMPO',
        '23.0': 'PÉNJAMO',
        '24.0': 'PUEBLO NUEVO',
        '25.0': 'PURÍSIMA DEL RINCÓN',
        '26.0': 'ROMITA',
        '27.0': 'SALAMANCA',
        '28.0': 'SALVATIERRA',
        '29.0': 'SAN DIEGO DE LA UNIÓN',
        '30.0': 'SAN FELIPE',
        '31.0': 'SAN FRANCISCO DEL RINCÓN',
        '32.0': 'SAN JOSÉ ITURBIDE',
        '33.0': 'SAN LUIS DE LA PAZ',
        '34.0': 'SANTA CATARINA',
        '35.0': 'SANTA CRUZ DE JUVENTINO ROSAS',
        '36.0': 'SANTIAGO MARAVATÍO',
        '37.0': 'SILAO DE LA VICTORIA',
        '38.0': 'TARANDACUAO',
        '39.0': 'TARIMORO',
        '40.0': 'TIERRA BLANCA',
        '41.0': 'URIANGATO',
        '42.0': 'VALLE DE SANTIAGO',
        '43.0': 'VICTORIA',
        '44.0': 'VILLAGRÁN',
        '45.0': 'XICHÚ',
        '46.0': 'YURIRIA'
    },
    'GUERRERO': {
        '1.0': 'ACAPULCO DE JUÁREZ',
        '2.0': 'AHUACUOTZINGO',
        '3.0': 'AJUCHITLÁN DEL PROGRESO',
        '4.0': 'ALCOZAUCA DE GUERRERO',
        '5.0': 'ALPOYECA',
        '6.0': 'APAXTLA',
        '7.0': 'ARIO DE ROSALES',
        '8.0': 'ATENANGO DEL RÍO',
        '9.0': 'ATLAMAJALCINGO DEL MONTE',
        '10.0': 'ATLIXTAC',
        '11.0': 'ATOYAC DE ÁLVAREZ',
        '12.0': 'AYUTLA DE LOS LIBRES',
        '13.0': 'AZOYÚ',
        '14.0': 'BENITO JUÁREZ',
        '15.0': 'BUENAVISTA DE CUÉLLAR',
        '16.0': 'COAHUAYUTLA DE JOSÉ MARÍA IZAZAGA',
        '17.0': 'COCULA',
        '18.0': 'COPALA',
        '19.0': 'COPALILLO',
        '20.0': 'COPANATOYAC',
        '21.0': 'COYUCA DE BENÍTEZ',
        '22.0': 'COYUCA DE CATALÁN',
        '23.0': 'CUAJINICUILAPA',
        '24.0': 'CUALAC',
        '25.0': 'CUETZALA DEL PROGRESO',
        '26.0': 'CUTZAMALA DE PINZÓN',
        '27.0': 'CHILAPA DE ÁLVAREZ',
        '28.0': 'CHILPANCINGO DE LOS BRAVO',
        '29.0': 'FLORENCIO VILLARREAL',
        '30.0': 'GENERAL HELIODORO CASTILLO',
        '31.0': 'HUAMUXTITLÁN',
        '32.0': 'HUITZUCO DE LOS FIGUEROA',
        '33.0': 'IGUALA DE LA INDEPENDENCIA',
        '34.0': 'IGUALAPA',
        '35.0': 'IXCATEOPAN DE CUAUHTÉMOC',
        '36.0': 'ZIHUATANEJO DE AZUETA',
        '37.0': 'JUAN R. ESCUDERO',
        '38.0': 'LEONARDO BRAVO',
        '39.0': 'MALINALTEPEC',
        '40.0': 'MÁRTIR DE CUILAPAN',
        '41.0': 'METLATÓNOC',
        '42.0': 'MOCHITLÁN',
        '43.0': 'OLINALÁ',
        '44.0': 'OMETEPEC',
        '45.0': 'PEDRO ASCENCIO ALQUISIRAS',
        '46.0': 'PETATLÁN',
        '47.0': 'PILCAYA',
        '48.0': 'PUNGARABATO',
        '49.0': 'QUECHULTENANGO',
        '50.0': 'SAN LUIS ACATLÁN',
        '51.0': 'SAN MARCOS',
        '52.0': 'SAN MIGUEL TOTOLAPAN',
        '53.0': 'TAXCO DE ALARCÓN',
        '54.0': 'TECOANAPA',
        '55.0': 'TÉCPAN DE GALEANA',
        '56.0': 'TELLOLOAPAN',
        '57.0': 'TEPECOACUILCO DE TRUJANO',
        '58.0': 'TETIPAC',
        '59.0': 'TIXTLA DE GUERRERO',
        '60.0': 'TLACOACHISTLAHUACA',
        '61.0': 'TLACOAPA',
        '62.0': 'TLALCHAPA',
        '63.0': 'TLALIXTAQUILLA DE MALDONADO',
        '64.0': 'TLAPA DE COMONFORT',
        '65.0': 'TLAPEHUALA',
        '66.0': 'LA UNIÓN DE ISIDORO MONTES DE OCA',
        '67.0': 'XALPATLÁHUAC',
        '68.0': 'XOCHIHUEHUETLÁN',
        '69.0': 'XOCHISTLAHUACA',
        '70.0': 'ZAPOTITLÁN TABLAS',
        '71.0': 'ZIRÁNDARO',
        '72.0': 'ZITLALA'
    },
    'HIDALGO': {
        '1.0': 'ACATLÁN',
        '2.0': 'ACAXOCHITLÁN',
        '3.0': 'ACTOPAN',
        '4.0': 'AGUA BLANCA DE ITURBIDE',
        '5.0': 'AJACUBA',
        '6.0': 'ALFAJAYUCAN',
        '7.0': 'ALMOLOYA',
        '8.0': 'APAN',
        '9.0': 'EL ARENAL',
        '10.0': 'ATITALAQUIA',
        '11.0': 'ATLAPEXCO',
        '12.0': 'ATOTONILCO EL GRANDE',
        '13.0': 'ATOTONILCO DE TULA',
        '14.0': 'CALNALI',
        '15.0': 'CARDONAL',
        '16.0': 'CUAUTEPEC DE HINOJOSA',
        '17.0': 'CHAPANTONGO',
        '18.0': 'CHAPULHUACÁN',
        '19.0': 'CHILCUAUTLA',
        '20.0': 'EPAZOYUCAN',
        '21.0': 'FRANCISCO I. MADERO',
        '22.0': 'HUASCA DE OCAMPO',
        '23.0': 'HUAUTLA',
        '24.0': 'HUAZALINGO',
        '25.0': 'HUEHUETLA',
        '26.0': 'HUEJUTLA DE REYES',
        '27.0': 'HUICHAPAN',
        '28.0': 'IXMIQUILPAN',
        '29.0': 'JACALA DE LEDEZMA',
        '30.0': 'JALTOCÁN',
        '31.0': 'JUÁREZ HIDALGO',
        '32.0': 'LOLOTLA',
        '33.0': 'METEPEC',
        '34.0': 'SAN AGUSTÍN METZQUITITLÁN',
        '35.0': 'METZTITLÁN',
        '36.0': 'MINERAL DEL CHICO',
        '37.0': 'MINERAL DEL MONTE',
        '38.0': 'MINERAL DE LA REFORMA',
        '39.0': 'MIXQUIAHUALA DE JUÁREZ',
        '40.0': 'MOLANGO DE ESCAMILLA',
        '41.0': 'NICOLÁS FLORES',
        '42.0': 'NOPALA DE VILLAGRÁN',
        '43.0': 'OMITLÁN DE JUÁREZ',
        '44.0': 'SAN FELIPE ORIZATLÁN',
        '45.0': 'PACULA',
        '46.0': 'PACHUCA DE SOTO',
        '47.0': 'PISAFLORES',
        '48.0': 'PROGRESO DE OBREGÓN',
        '49.0': 'SAN AGUSTÍN TLAXIACA',
        '50.0': 'SAN BARTOLO TUTOTEPEC',
        '51.0': 'SAN SALVADOR',
        '52.0': 'SANTIAGO DE ANAYA',
        '53.0': 'SINGUILUCAN',
        '54.0': 'TASQUILLO',
        '55.0': 'TECOZAUTLA',
        '56.0': 'TENANGO DE DORIA',
        '57.0': 'TEPEAPULCO',
        '58.0': 'TEPEHUACÁN DE GUERRERO',
        '59.0': 'TEPEJI DEL RÍO DE OCAMPO',
        '60.0': 'TEPETITLÁN',
        '61.0': 'TETEPANGO',
        '62.0': 'VILLA DE TEZONTEPEC',
        '63.0': 'TEZONTEPEC DE ALDAMA',
        '64.0': 'TIANGUISTENGO',
        '65.0': 'TIZAYUCA',
        '66.0': 'TLAHUELILPAN',
        '67.0': 'TLAHUILTEPA',
        '68.0': 'TLANCHINOL',
        '69.0': 'TLAXCOAPAN',
        '70.0': 'TULA DE ALLENDE',
        '71.0': 'TULANCINGO DE BRAVO',
        '72.0': 'XOCHIATIPAN',
        '73.0': 'XOCHICOATLÁN',
        '74.0': 'YAHUALICA',
        '75.0': 'ZACUALTIPÁN DE ÁNGELES',
        '76.0': 'ZAPOTLÁN DE JUÁREZ',
        '77.0': 'ZEMPOALA',
        '78.0': 'ZIMAPÁN'
    },
    'JALISCO': {
        '1.0': 'ACATIC',
        '2.0': 'ACATLÁN DE JUÁREZ',
        '3.0': 'AHUALULCO DE MERCADO',
        '4.0': 'AMACUECA',
        '5.0': 'AMATITÁN',
        '6.0': 'AMECA',
        '7.0': 'SAN JUANITO DE ESCOBEDO',
        '8.0': 'ARANDAS',
        '9.0': 'EL ARENAL',
        '10.0': 'ATEMAJAC DE BRIZUELA',
        '11.0': 'ATENGO',
        '12.0': 'ATENGUILLO',
        '13.0': 'ATOYAC',
        '14.0': 'AUTLÁN DE NAVARRO',
        '15.0': 'AYOTLÁN',
        '16.0': 'AYUTLA',
        '17.0': 'LA BARCA',
        '18.0': 'BOLAÑOS',
        '19.0': 'CABO CORRIENTES',
        '20.0': 'CASIMIRO CASTILLO',
        '21.0': 'CIHUATLÁN',
        '22.0': 'ZAPOTLÁN EL GRANDE',
        '23.0': 'COCULA',
        '24.0': 'COLOTLÁN',
        '25.0': 'CONCEPCIÓN DE BUENOS AIRES',
        '26.0': 'CUAUTITLÁN DE GARCÍA BARRAGÁN',
        '27.0': 'CUAUTLA',
        '28.0': 'CUQUIO',
        '29.0': 'CHAPALA',
        '30.0': 'CHIMALTITÁN',
        '31.0': 'CHIQUILISTLÁN',
        '32.0': 'DEGOLLADO',
        '33.0': 'EJUTLA',
        '34.0': 'ENCARNACIÓN DE DÍAZ',
        '35.0': 'ETZATLÁN',
        '36.0': 'EL GRULLO',
        '37.0': 'GUACHINANGO',
        '38.0': 'GUADALAJARA',
        '39.0': 'HOSTOTIPAQUILLO',
        '40.0': 'HUEJÚCAR',
        '41.0': 'HUEJUQUILLA EL ALTO',
        '42.0': 'LA HUERTA',
        '43.0': 'IXTLAHUACÁN DE LOS MEMBRILLOS',
        '44.0': 'IXTLAHUACÁN DEL RÍO',
        '45.0': 'JALOSTOTITLÁN',
        '46.0': 'JAMAY',
        '47.0': 'JESÚS MARÍA',
        '48.0': 'JILOTLÁN DE LOS DOLORES',
        '49.0': 'JOCOTEPEC',
        '50.0': 'JUANACATLÁN',
        '51.0': 'JUCHITLÁN',
        '52.0': 'LAGOS DE MORENO',
        '53.0': 'EL LIMÓN',
        '54.0': 'MAGDALENA',
        '55.0': 'SANTA MARÍA DEL ORO',
        '56.0': 'LA MANZANILLA DE LA PAZ',
        '57.0': 'MASCOTA',
        '58.0': 'MAZAMITLA',
        '59.0': 'MEXTICACÁN',
        '60.0': 'MEZQUITIC',
        '61.0': 'MIXTLÁN',
        '62.0': 'OCOTLÁN',
        '63.0': 'OJUELOS DE JALISCO',
        '64.0': 'PIHUAMO',
        '65.0': 'PONCITLÁN',
        '66.0': 'PUERTO VALLARTA',
        '67.0': 'VILLA PURIFICACIÓN',
        '68.0': 'QUITUPAN',
        '69.0': 'EL SALTO',
        '70.0': 'SAN CRISTÓBAL DE LA BARRANCA',
        '71.0': 'SAN DIEGO DE ALEJANDRÍA',
        '72.0': 'SAN JUAN DE LOS LAGOS',
        '73.0': 'SAN JULIÁN',
        '74.0': 'SAN MARCOS',
        '75.0': 'SAN MARTÍN DE BOLAÑOS',
        '76.0': 'SAN MARTÍN HIDALGO',
        '77.0': 'SAN MIGUEL EL ALTO',
        '78.0': 'GÓMEZ FARÍAS',
        '79.0': 'SAN SEBASTIÁN DEL OESTE',
        '80.0': 'SANTA MARÍA DE LOS ÁNGELES',
        '81.0': 'SAYULA',
        '82.0': 'TALA',
        '83.0': 'TALPA DE ALLENDE',
        '84.0': 'TAMAZULA DE GORDIANO',
        '85.0': 'TAPALPA',
        '86.0': 'TECALITLÁN',
        '87.0': 'TECOLOTLÁN',
        '88.0': 'TEPATITLÁN DE MORELOS',
        '89.0': 'TEQUILA',
        '90.0': 'TEUCHITLÁN',
        '91.0': 'TIZAPÁN EL ALTO',
        '92.0': 'TLAJOMULCO DE ZÚÑIGA',
        '93.0': 'TLAQUEPAQUE',
        '94.0': 'TOLIMÁN',
        '95.0': 'TOMATLÁN',
        '96.0': 'TONALÁ',
        '97.0': 'TONAYA',
        '98.0': 'TONILA',
        '99.0': 'TOTATICHE',
        '100.0': 'TOTOTLÁN',
        '101.0': 'TUXCACUESCO',
        '102.0': 'TUXPAN',
        '103.0': 'UNIÓN DE SAN ANTONIO',
        '104.0': 'UNIÓN DE TULA',
        '105.0': 'VALLE DE GUADALUPE',
        '106.0': 'VALLE DE JUÁREZ',
        '107.0': 'SAN GABRIEL',
        '108.0': 'VILLA CORONA',
        '109.0': 'VILLA GUERRERO',
        '110.0': 'VILLA HIDALGO',
        '111.0': 'CAÑADAS DE OBREGÓN',
        '112.0': 'YAHUALICA DE GONZÁLEZ GALLO',
        '113.0': 'ZACOALCO DE TORRES',
        '114.0': 'ZAPOPAN',
        '115.0': 'ZAPOTILTIC',
        '116.0': 'ZAPOTITLÁN DE VADILLO',
        '117.0': 'ZAPOTLÁN DEL REY',
        '118.0': 'ZAPOTLANEJO',
        '119.0': 'SAN IGNACIO CERRO GORDO'
    },
    'MÉXICO': {
        '1.0': 'ACAMBAY DE RUÍZ CASTAÑEDA',
        '2.0': 'ACOLMAN',
        '3.0': 'ACULCO',
        '4.0': 'ALMOLOYA DE ALQUISIRAS',
        '5.0': 'ALMOLOYA DE JUÁREZ',
        '6.0': 'ALMOLOYA DEL RÍO',
        '7.0': 'AMANALCO',
        '8.0': 'AMATEPEC',
        '9.0': 'AMECAMECA',
        '10.0': 'APAXCO',
        '11.0': 'ATENCO',
        '12.0': 'ATIZAPÁN',
        '13.0': 'ATIZAPÁN DE ZARAGOZA',
        '14.0': 'ATLACOMULCO',
        '15.0': 'ATLAUTLA',
        '16.0': 'AXAPUSCO',
        '17.0': 'AYAPANGO',
        '18.0': 'CALIMAYA',
        '19.0': 'CAPULHUAC',
        '20.0': 'COACALCO DE BERRIOZÁBAL',
        '21.0': 'COATEPEC HARINAS',
        '22.0': 'COCOTITLÁN',
        '23.0': 'COYOTEPEC',
        '24.0': 'CUAUTITLÁN',
        '25.0': 'CHALCO',
        '26.0': 'CHAPA DE MOTA',
        '27.0': 'CHAPULTEPEC',
        '28.0': 'CHIAUTLA',
        '29.0': 'CHICOLOAPAN',
        '30.0': 'CHICONCUAC',
        '31.0': 'CHIMALHUACÁN',
        '32.0': 'DONATO GUERRA',
        '33.0': 'ECATEPEC DE MORELOS',
        '34.0': 'ECATZINGO',
        '35.0': 'HUEHUETOCA',
        '36.0': 'HUEYPOXTLA',
        '37.0': 'HUIXQUILUCAN',
        '38.0': 'ISIDRO FABELA',
        '39.0': 'IXTAPALUCA',
        '40.0': 'IXTAPAN DE LA SAL',
        '41.0': 'IXTAPAN DEL ORO',
        '42.0': 'IXTLAHUACA',
        '43.0': 'XALATLACO',
        '44.0': 'JALTENCO',
        '45.0': 'JILOTEPEC',
        '46.0': 'JILOTZINGO',
        '47.0': 'JIQUIPILCO',
        '48.0': 'JOCOTITLÁN',
        '49.0': 'JOQUICINGO',
        '50.0': 'JUCHITEPEC',
        '51.0': 'LERMA',
        '52.0': 'MALINALCO',
        '53.0': 'MELCHOR OCAMPO',
        '54.0': 'METEPEC',
        '55.0': 'MEXICALTZINGO',
        '56.0': 'MORELOS',
        '57.0': 'NAUCALPAN DE JUÁREZ',
        '58.0': 'NEZAHUALCÓYOTL',
        '59.0': 'NEXTLALPAN',
        '60.0': 'NICOLÁS ROMERO',
        '61.0': 'NOPALTEPEC',
        '62.0': 'OCOYOACAC',
        '63.0': 'OCUILAN',
        '64.0': 'EL ORO',
        '65.0': 'OTUMBA',
        '66.0': 'OTZOLOAPAN',
        '67.0': 'OTZOLOTEPEC',
        '68.0': 'OZUMBA',
        '69.0': 'PAPALOTLA',
        '70.0': 'LA PAZ',
        '71.0': 'POLOTITLÁN',
        '72.0': 'RAYÓN',
        '73.0': 'SAN ANTONIO LA ISLA',
        '74.0': 'SAN FELIPE DEL PROGRESO',
        '75.0': 'SAN MARTÍN DE LAS PIRÁMIDES',
        '76.0': 'SAN MATEO ATENCO',
        '77.0': 'SAN SIMÓN DE GUERRERO',
        '78.0': 'SANTO TOMÁS',
        '79.0': 'SOYANIQUILPAN DE JUÁREZ',
        '80.0': 'SULTEPEC',
        '81.0': 'TECÁMAC',
        '82.0': 'TEJUPILCO',
        '83.0': 'TEMAMATLA',
        '84.0': 'TEMASCALAPA',
        '85.0': 'TEMASCALCINGO',
        '86.0': 'TEMASCALTEPEC',
        '87.0': 'TEMOAYA',
        '88.0': 'TENANCINGO',
        '89.0': 'TENANGO DEL AIRE',
        '90.0': 'TENANGO DEL VALLE',
        '91.0': 'TEOLOYUCAN',
        '92.0': 'TEOTIHUACÁN',
        '93.0': 'TEPETLAOXTOC',
        '94.0': 'TEPETLIXPA',
        '95.0': 'TEPOTZOTLÁN',
        '96.0': 'TEQUIXQUIAC',
        '97.0': 'TEXCALTITLÁN',
        '98.0': 'TEXCALYACAC',
        '99.0': 'TEXCOCO',
        '100.0': 'TEZOYUCA',
        '101.0': 'TIANGUISTENCO',
        '102.0': 'TIMILPAN',
        '103.0': 'TLALMANALCO',
        '104.0': 'TLALNEPANTLA DE BAZ',
        '105.0': 'TLATLAYA',
        '106.0': 'TOLUCA',
        '107.0': 'TONATICO',
        '108.0': 'TULTEPEC',
        '109.0': 'TULTITLÁN',
        '110.0': 'VALLE DE BRAVO',
        '111.0': 'VILLA DE ALLENDE',
        '112.0': 'VILLA DEL CARBÓN',
        '113.0': 'VILLA GUERRERO',
        '114.0': 'VILLA VICTORIA',
        '115.0': 'XONACATLÁN',
        '116.0': 'ZACAZONAPAN',
        '117.0': 'ZACUALPAN',
        '118.0': 'ZINACANTEPEC',
        '119.0': 'ZUMPAHUACÁN',
        '120.0': 'ZUMPANGO'
    },
    'MICHOACAN DE OCAMPO':{
        '1.0': 'ACUITZIO',
        '2.0': 'AGUILILLA',
        '3.0': 'ÁLVARO OBREGÓN',
        '4.0': 'ANGAMACUTIRO',
        '5.0': 'ANGANGUEO',
        '6.0': 'APATZINGÁN',
        '7.0': 'AQUILA',
        '8.0': 'ARIO',
        '9.0': 'ARTEAGA',
        '10.0': 'BRISEÑAS',
        '11.0': 'BUENAVISTA',
        '12.0': 'CARÁCUARO',
        '13.0': 'COAHUAYANA',
        '14.0': 'COALCOMÁN DE VÁZQUEZ PALLARES',
        '15.0': 'COENEO',
        '16.0': 'CONTEPEC',
        '17.0': 'COPÁNDARO',
        '18.0': 'COTIJA',
        '19.0': 'CUITZEO',
        '20.0': 'CHARAPAN',
        '21.0': 'CHARO',
        '22.0': 'CHAVINDA',
        '23.0': 'CHERÁN',
        '24.0': 'CHILCHOTA',
        '25.0': 'CHINICUILA',
        '26.0': 'CHUCÁNDIRO',
        '27.0': 'CHURINTZIO',
        '28.0': 'CHURUMUCO',
        '29.0': 'ECUANDUREO',
        '30.0': 'EPITACIO HUERTA',
        '31.0': 'ERONGARÍCUARO',
        '32.0': 'GABRIEL ZAMORA',
        '33.0': 'HIDALGO',
        '34.0': 'HUANDACAREO',
        '35.0': 'HUANIQUEO',
        '36.0': 'HUETAMO',
        '37.0': 'HUIRAMBA',
        '38.0': 'INDAPARAPEO',
        '39.0': 'IRIMBO',
        '40.0': 'IXTLÁN',
        '41.0': 'JACONA',
        '42.0': 'JIMÉNEZ',
        '43.0': 'JIQUILPAN',
        '44.0': 'JUÁREZ',
        '45.0': 'JUNGAPEO',
        '46.0': 'LAGUNILLAS',
        '47.0': 'MADERO',
        '48.0': 'MARAVATÍO',
        '49.0': 'MARCOS CASTELLANOS',
        '50.0': 'LÁZARO CÁRDENAS',
        '51.0': 'MORELIA',
        '52.0': 'MORELOS',
        '53.0': 'MÚGICA',
        '54.0': 'NAHUATZEN',
        '55.0': 'NOCUPÉTARO',
        '56.0': 'NUEVO PARANGARICUTIRO',
        '57.0': 'NUEVO URECHO',
        '58.0': 'NUMARÁN',
        '59.0': 'OCAMPO',
        '60.0': 'PAJACUARÁN',
        '61.0': 'PANINDÍCUARO',
        '62.0': 'PARÁCUARO',
        '63.0': 'PARACHO',
        '64.0': 'PÁTZCUARO',
        '65.0': 'PENJAMILLO',
        '66.0': 'PERIBÁN',
        '67.0': 'LA PIEDAD',
        '68.0': 'PURÉPERO',
        '69.0': 'PURUÁNDIRO',
        '70.0': 'QUERÉNDARO',
        '71.0': 'QUIROGA',
        '72.0': 'COJUMATLÁN DE RÉGULES',
        '73.0': 'REYES',
        '74.0': 'SAHUAYO',
        '75.0': 'SAN LUCAS',
        '76.0': 'SANTA ANA MAYA',
        '77.0': 'SALVADOR ESCALANTE',
        '78.0': 'SENGUIO',
        '79.0': 'SUSUPUATO',
        '80.0': 'TACÁMBARO',
        '81.0': 'TANCÍTARO',
        '82.0': 'TANGAMANDAPIO',
        '83.0': 'TANGANCÍCUARO',
        '84.0': 'TANHUATO',
        '85.0': 'TARETAN',
        '86.0': 'TARÍMBARO',
        '87.0': 'TEPALCATEPEC',
        '88.0': 'TINGAMBATO',
        '89.0': 'TINGÜINDÍN',
        '90.0': 'TIQUICHEO DE NICOLÁS ROMERO',
        '91.0': 'TLALPUJAHUA',
        '92.0': 'TLAZAZALCA',
        '93.0': 'TOCUMBO',
        '94.0': 'TUMBISCATÍO',
        '95.0': 'TURICATO',
        '96.0': 'TUXPAN',
        '97.0': 'TUZANTLA',
        '98.0': 'TZINTZUNTZAN',
        '99.0': 'TZITZIO',
        '100.0': 'URUAPAN',
        '101.0': 'VENUSTIANO CARRANZA',
        '102.0': 'VILLAMAR',
        '103.0': 'VISTA HERMOSA',
        '104.0': 'YURÉCUARO',
        '105.0': 'ZACAPU',
        '106.0': 'ZAMORA',
        '107.0': 'ZINÁPARO',
        '108.0': 'ZINAPÉCUARO',
        '109.0': 'ZIRACUARETIRO',
        '110.0': 'ZITÁCUARO',
        '111.0': 'JOSÉ SIXTO VERDUZCO'
    },
    'MORELOS': {
        '1.0': 'AMACUZAC',
        '2.0': 'ATLATLAHUCAN',
        '3.0': 'AXOCHIAPAN',
        '4.0': 'AYALA',
        '5.0': 'COATLÁN DEL RÍO',
        '6.0': 'CUAUTLA',
        '7.0': 'CUERNAVACA',
        '8.0': 'EMILIANO ZAPATA',
        '9.0': 'HUITZILAC',
        '10.0': 'JANTETELCO',
        '11.0': 'JIUTEPEC',
        '12.0': 'JONACATEPEC DE LEANDRO VALLE',
        '13.0': 'MAZATEPEC',
        '14.0': 'MIACATLÁN',
        '15.0': 'OCUITUCO',
        '16.0': 'PUENTE DE IXTLA',
        '17.0': 'TEMIXCO',
        '18.0': 'TEPALCINGO',
        '19.0': 'TEPOZTLÁN',
        '20.0': 'TETECALA',
        '21.0': 'TETELA DEL VOLCÁN',
        '22.0': 'TLALNEPANTLA',
        '23.0': 'TLAYACAPAN',
        '24.0': 'TOTOLAPAN',
        '25.0': 'XOCHITEPEC',
        '26.0': 'YAUTEPEC',
        '27.0': 'YECAPIXTLA',
        '28.0': 'ZACATEPEC',
        '29.0': 'TLALTIZAPÁN DE ZAPATA',
        '30.0': 'TLAQUILTENANGO',
        '31.0': 'CUATLA',
        '32.0': 'COATETELCO',
        '33.0': 'HUEYAPAN',
        '34.0': 'XOCHILTEPEC',
        '35.0': 'ZACUALPAN',
        '36.0': 'JONACATEPEC'
    },
    'NAYARIT': {
        '1.0': 'ACAPONETA',
        '2.0': 'AHUACATLÁN',
        '3.0': 'AMATLÁN DE CAÑAS',
        '4.0': 'COMPOSTELA',
        '5.0': 'HUAJICORI',
        '6.0': 'IXTLÁN DEL RÍO',
        '7.0': 'JALA',
        '8.0': 'XALISCO',
        '9.0': 'DEL NAYAR',
        '10.0': 'ROSAMORADA',
        '11.0': 'RUÍZ',
        '12.0': 'SAN BLAS',
        '13.0': 'SAN PEDRO LAGUNILLAS',
        '14.0': 'SANTA MARÍA DEL ORO',
        '15.0': 'SANTIAGO IXCUINTLA',
        '16.0': 'TECUALA',
        '17.0': 'TEPIC',
        '18.0': 'TUXPAN',
        '19.0': 'LA YESCA',
        '20.0': 'BAHÍA DE BANDERAS'
    },
    'NUEVO LEÓN': {
        '1.0': 'ABASOLO',
        '2.0': 'AGUALEGUAS',
        '3.0': 'LOS ALDAMAS',
        '4.0': 'ALLENDE',
        '5.0': 'ANÁHUAC',
        '6.0': 'APODACA',
        '7.0': 'ARAMBERRI',
        '8.0': 'BUSTAMANTE',
        '9.0': 'CADEREYTA JIMÉNEZ',
        '10.0': 'EL CARMEN',
        '11.0': 'CERRALVO',
        '12.0': 'CIÉNEGA DE FLORES',
        '13.0': 'CHINA',
        '14.0': 'DOCTOR ARROYO',
        '15.0': 'DOCTOR COSS',
        '16.0': 'DOCTOR GONZÁLEZ',
        '17.0': 'GALEANA',
        '18.0': 'GARCÍA',
        '19.0': 'SAN PEDRO GARZA GARCÍA',
        '20.0': 'GENERAL BRAVO',
        '21.0': 'GENERAL ESCOBEDO',
        '22.0': 'GENERAL TERÁN',
        '23.0': 'GENERAL TREVIÑO',
        '24.0': 'GENERAL ZARAGOZA',
        '25.0': 'GENERAL ZUAZUA',
        '26.0': 'GUADALUPE',
        '27.0': 'HIDALGO',
        '28.0': 'HIGUERAS',
        '29.0': 'HUALAHUISES',
        '30.0': 'ITURBIDE',
        '31.0': 'JUÁREZ',
        '32.0': 'LAMPAZOS DE NARANJO',
        '33.0': 'LINARES',
        '34.0': 'MARÍN',
        '35.0': 'MELCHOR OCAMPO',
        '36.0': 'MIER Y NORIEGA',
        '37.0': 'MINA',
        '38.0': 'MONTEMORELOS',
        '39.0': 'MONTERREY',
        '40.0': 'PARÁS',
        '41.0': 'PESQUERÍA',
        '42.0': 'RAYONES',
        '43.0': 'SABINAS HIDALGO',
        '44.0': 'SALINAS VICTORIA',
        '45.0': 'SAN NICOLÁS DE LOS GARZA',
        '46.0': 'SAN PEDRO GARZA GARCÍA',
        '47.0': 'SANTA CATARINA',
        '48.0': 'SANTIAGO',
        '49.0': 'VALLECILLO',
        '50.0': 'VILLALDAMA'
    },
    'OAXACA': {
        '1.0': 'ABEJONES',
        '2.0': 'ACATLÁN DE PÉREZ FIGUEROA',
        '3.0': 'ASUNCIÓN CACALOTEPEC',
        '4.0': 'ASUNCIÓN CUYOTEPEJI',
        '5.0': 'ASUNCIÓN IXTALTEPEC',
        '6.0': 'ASUNCIÓN NOCHIXTLÁN',
        '7.0': 'ASUNCIÓN OCOTLÁN',
        '8.0': 'ASUNCIÓN TLACOLULITA',
        '9.0': 'AYOQUEZCO DE ALDAMA',
        '10.0': 'AYOTZINTEPEC',
        '11.0': 'CALIHUALÁ',
        '12.0': 'CANDELARIA LOXICHA',
        '13.0': 'CIÉNEGAS DE ZIMATLÁN',
        '14.0': 'COATECAS ALTAS',
        '15.0': 'COICOYÁN DE LAS FLORES',
        '16.0': 'CIUDAD IXTEPEC',
        '17.0': 'CONSTANCIA DEL ROSARIO',
        '18.0': 'COSOLAPA',
        '19.0': 'COSOLTEPEC',
        '20.0': 'CUILÁPAM DE GUERRERO',
        '21.0': 'CHAHUITES',
        '22.0': 'CHALCATONGO DE HIDALGO',
        '23.0': 'CHICOLOAPAN',
        '24.0': 'CHIMALAPA',
        '25.0': 'COLONIA ALFREDO BONFIL',
        '26.0': 'EJUTLA DE CRESPO',
        '27.0': 'EL BARRIO DE LA SOLEDAD',
        '28.0': 'EL ESPINAL',
        '29.0': 'FRESNILLO DE TRUJANO',
        '30.0': 'GUADALUPE DE RAMÍREZ',
        '31.0': 'GUELATAO DE JUÁREZ',
        '32.0': 'GUEVEA DE HUMBOLDT',
        '33.0': 'HEROICA CIUDAD DE EJUTLA DE CRESPO',
        '34.0': 'HEROICA CIUDAD DE HUAJUAPAN DE LEÓN',
        '35.0': 'HEROICA CIUDAD DE TLAXIACO',
        '36.0': 'HUAUTEPEC',
        '37.0': 'HUAUTLA DE JIMÉNEZ',
        '38.0': 'IXTLÁN DE JUÁREZ',
        '39.0': 'JUCHITÁN DE ZARAGOZA',
        '40.0': 'LOMA BONITA',
        '41.0': 'MAGDALENA APASCO',
        '42.0': 'MAGDALENA JALTEPEC',
        '43.0': 'MAGDALENA MIXTEPEC',
        '44.0': 'MAGDALENA OCOTLÁN',
        '45.0': 'MAGDALENA PEÑASCO',
        '46.0': 'MAGDALENA TEITIPAC',
        '47.0': 'MAGDALENA TEQUISISTLÁN',
        '48.0': 'MAGDALENA TLACOTEPEC',
        '49.0': 'MAGDALENA YODOCONO DE PORFIRIO DÍAZ',
        '50.0': 'MAGDALENA ZAHUATLÁN',
        '51.0': 'MARISCALA DE JUÁREZ',
        '52.0': 'MATÍAS ROMERO AVENDAÑO',
        '53.0': 'MAZATLÁN VILLA DE FLORES',
        '54.0': 'MIAHUATLÁN DE PORFIRIO DÍAZ',
        '55.0': 'MIXISTLÁN DE LA REFORMA',
        '56.0': 'MONJAS',
        '57.0': 'NATIVIDAD',
        '58.0': 'NAUPAN',
        '59.0': 'NAZARENO ETLA',
        '60.0': 'NEJAPA DE MADERO',
        '61.0': 'NUEVO ZOQUIÁPAM',
        '62.0': 'OAXACA DE JUÁREZ',
        '63.0': 'OCOTLÁN DE MORELOS',
        '64.0': 'PINOTEPA NACIONAL',
        '65.0': 'PUTLA VILLA DE GUERRERO',
        '66.0': 'SALINA CRUZ',
        '67.0': 'SAN AGUSTÍN AMATENGO',
        '68.0': 'SAN AGUSTÍN CHAYUCO',
        '69.0': 'SAN AGUSTÍN DE LAS JUNTAS',
        '70.0': 'SAN AGUSTÍN ETLA',
        '71.0': 'SAN AGUSTÍN LOXICHA',
        '72.0': 'SAN AGUSTÍN TLACOTEPEC',
        '73.0': 'SAN AGUSTÍN YATARENI',
        '74.0': 'SAN ANDRÉS CABEZAS',
        '75.0': 'SAN ANDRÉS CHICHOHUA',
        '76.0': 'SAN ANDRÉS HUAXPALTEPEC',
        '77.0': 'SAN ANDRÉS HUAYÁPAM',
        '78.0': 'SAN ANDRÉS IXTLAHUACA',
        '79.0': 'SAN ANDRÉS LAGUNAS',
        '80.0': 'SAN ANDRÉS NATIVITAS',
        '81.0': 'SAN ANDRÉS PAXTLÁN',
        '82.0': 'SAN ANDRÉS SINACHÉ',
        '83.0': 'SAN ANDRÉS SOLAGA',
        '84.0': 'SAN ANDRÉS TEOTILÁLPAM',
        '85.0': 'SAN ANDRÉS TLÁPACOYA',
        '86.0': 'SAN ANDRÉS YAA',
        '87.0': 'SAN ANDRÉS ZAUTLA',
        '88.0': 'SAN ANTONIO ACATLÁN',
        '89.0': 'SAN ANTONIO CASTILLO VELASCO',
        '90.0': 'SAN ANTONIO DE LA CAL',
        '91.0': 'SAN ANTONIO NANAHUATIPAM',
        '92.0': 'SAN ANTONIO SINACHÉ',
        '93.0': 'SAN ANTONIO TECÓMITL',
        '94.0': 'SAN ANTONIO TEPETLAPA',
        '95.0': 'SAN ANTONIO TEPOSCOLULA',
        '96.0': 'SAN ANTONIO TEXCOCO',
        '97.0': 'SAN ANTONIO YAUTEPEC',
        '98.0': 'SAN BALTASAR CHICHICAPAN',
        '99.0': 'SAN BALTASAR LOXICHA',
        '100.0': 'SAN BALTASAR YAUTEPEC',
         '101.0': 'SAN BARTOLO AYAUHTEPEC',
        '102.0': 'SAN BARTOLO COYOTEPEC',
        '103.0': 'SAN BARTOLOMÉ LOXICHA',
        '104.0': 'SAN BARTOLOMÉ QUIALANA',
        '105.0': 'SAN BARTOLOMÉ YUCUAÑE',
        '106.0': 'SAN BARTOLOMÉ ZOOGOCHO',
        '107.0': 'SAN BARTOLOMÉ ZOZOLOPAN',
        '108.0': 'SAN BARTOLOMÉ ZOZOCOLCO',
        '109.0': 'SAN BERNARDO MIXTEPEC',
        '110.0': 'SAN CARLOS YAUTEPEC',
        '111.0': 'SAN CRISTÓBAL AMATLÁN',
        '112.0': 'SAN CRISTÓBAL LACHIRIOAG',
        '113.0': 'SAN CRISTÓBAL SUCHIXTLAHUACA',
        '114.0': 'SAN DIONISIO DEL MAR',
        '115.0': 'SAN DIONISIO OCOTEPEC',
        '116.0': 'SAN DIONISIO OCOTLÁN',
        '117.0': 'SAN ESTEBAN ATLATAHUCA',
        '118.0': 'SAN FELIPE JALAPA DE DÍAZ',
        '119.0': 'SAN FELIPE TEJALÁPAM',
        '120.0': 'SAN FELIPE USILA',
        '121.0': 'SAN FRANCISCO CAHUACUÁ',
        '122.0': 'SAN FRANCISCO CHINDÚA',
        '123.0': 'SAN FRANCISCO DEL MAR',
        '124.0': 'SAN FRANCISCO HUAJOLÓTITLAN',
        '125.0': 'SAN FRANCISCO IXHUATÁN',
        '126.0': 'SAN FRANCISCO JALTEPETONGO',
        '127.0': 'SAN FRANCISCO LACHIGOLÓ',
        '128.0': 'SAN FRANCISCO LOGUECHE',
        '129.0': 'SAN FRANCISCO NUXAÑO',
        '130.0': 'SAN FRANCISCO OZOLOTEPEC',
        '131.0': 'SAN FRANCISCO SOLA',
        '132.0': 'SAN FRANCISCO TELIXTLAHUACA',
        '133.0': 'SAN FRANCISCO TEOPAN',
        '134.0': 'SAN FRANCISCO TLAPANCINGO',
        '135.0': 'SAN GABRIEL MIXTEPEC',
        '136.0': 'SAN ILDEFONSO AMATLÁN',
        '137.0': 'SAN ILDEFONSO SOLA',
        '138.0': 'SAN ILDEFONSO VILLA ALTA',
        '139.0': 'SAN JACINTO AMILPAS',
        '140.0': 'SAN JACINTO TLACOTEPEC',
        '141.0': 'SAN JERÓNIMO COATLÁN',
        '142.0': 'SAN JERÓNIMO SILACAYOAPILLA',
        '143.0': 'SAN JERÓNIMO SOSOLA',
        '144.0': 'SAN JERÓNIMO TAVICHE',
        '145.0': 'SAN JERÓNIMO TECOATL',
        '146.0': 'SAN JORGE NUCHITA',
        '147.0': 'SAN JOSÉ AYUQUILA',
        '148.0': 'SAN JOSÉ CHILTEPEC',
        '149.0': 'SAN JOSÉ DEL PEÑASCO',
        '150.0': 'SAN JOSÉ ESTANCIA GRANDE',
        '151.0': 'SAN JOSÉ INDEPENDENCIA',
        '152.0': 'SAN JOSÉ LACHIGUIRI',
        '153.0': 'SAN JOSÉ TENANGO',
        '154.0': 'SAN JUAN ACHIUTLA',
        '155.0': 'SAN JUAN ATEPEC',
        '156.0': 'SAN JUAN BAUTISTA ATATLAHUCA',
        '157.0': 'SAN JUAN BAUTISTA COIXTLAHUACA',
        '158.0': 'SAN JUAN BAUTISTA CUICATLÁN',
        '159.0': 'SAN JUAN BAUTISTA GUELACHE',
        '160.0': 'SAN JUAN BAUTISTA JAYACATLÁN',
        '161.0': 'SAN JUAN BAUTISTA LO DE SOTO',
        '162.0': 'SAN JUAN BAUTISTA SUCHITEPEC',
        '163.0': 'SAN JUAN BAUTISTA TLACOATZINTEPEC',
        '164.0': 'SAN JUAN BAUTISTA TLACHICHILCO',
        '165.0': 'SAN JUAN BAUTISTA TLALTEPANGO',
        '166.0': 'SAN JUAN BAUTISTA TONAMECA',
        '167.0': 'SAN JUAN BAUTISTA TOTOLTEPEC',
        '168.0': 'SAN JUAN CAJONOS',
        '169.0': 'SAN JUAN CASTILLO',
        '170.0': 'SAN JUAN CHICOMEZUCHIL',
        '171.0': 'SAN JUAN CHILATECA',
        '172.0': 'SAN JUAN CUAUTLA',
        '173.0': 'SAN JUAN DIUXI',
        '174.0': 'SAN JUAN EVANGELISTA',
        '175.0': 'SAN JUAN GUICHICOVI',
        '176.0': 'SAN JUAN IHUALTEPEC',
        '177.0': 'SAN JUAN JUQUILA MIXES',
        '178.0': 'SAN JUAN JUQUILA VIJAYE',
        '179.0': 'SAN JUAN LACHAO',
        '180.0': 'SAN JUAN LACHIGALLA',
        '181.0': 'SAN JUAN LAJARCITO',
        '182.0': 'SAN JUAN LALANA',
        '183.0': 'SAN JUAN LALOPA',
        '184.0': 'SAN JUAN MAZATLÁN',
        '185.0': 'SAN JUAN MIXTEPEC',
        '186.0': 'SAN JUAN ÑUMI',
        '187.0': 'SAN JUAN OZOLOTEPEC',
        '188.0': 'SAN JUAN PETLAPA',
        '189.0': 'SAN JUAN QUIAHIJE',
        '190.0': 'SAN JUAN QUÍHUIJLO',
        '191.0': 'SAN JUAN SAYULTEPEC',
        '192.0': 'SAN JUAN TABAA',
        '193.0': 'SAN JUAN TAMAZOLA',
        '194.0': 'SAN JUAN TAPEXTLA',
        '195.0': 'SAN JUAN TEITA',
        '196.0': 'SAN JUAN TEITIPAC',
        '197.0': 'SAN JUAN TEPEUXILA',
        '198.0': 'SAN JUAN TEPOZCOLULA',
        '199.0': 'SAN JUAN VILLAHERMOSA',
        '200.0': 'SAN JUAN YUCUITA',
        '201.0': 'SAN LORENZO',
        '202.0': 'SAN LORENZO ALBARRADAS',
        '203.0': 'SAN LORENZO CACAOTEPEC',
        '204.0': 'SAN LORENZO CUAUNECUILTITLA',
        '205.0': 'SAN LORENZO TEXMELÚCAN',
        '206.0': 'SAN LORENZO VICTORIA',
        '207.0': 'SAN LUCAS CAMOTLÁN',
        '208.0': 'SAN LUCAS OJITLÁN',
        '209.0': 'SAN LUCAS QUIAVINÍ',
        '210.0': 'SAN LUCAS ZOQUIÁPAM',
        '211.0': 'SAN LUIS AMATLÁN',
        '212.0': 'SAN MARCIAL OZOLOTEPEC',
        '213.0': 'SAN MARCOS ARTEAGA',
        '214.0': 'SAN MARTÍN DE LOS CANSECOS',
        '215.0': 'SAN MARTÍN HUAMELÚLPAM',
        '216.0': 'SAN MARTÍN ITUNYOSO',
        '217.0': 'SAN MARTÍN LACHILÁ',
        '218.0': 'SAN MARTÍN PERAS',
        '219.0': 'SAN MARTÍN TILCAJETE',
        '220.0': 'SAN MARTÍN TOXPALAN',
        '221.0': 'SAN MARTÍN ZOQUITLÁN',
        '222.0': 'SAN MATEO CAJONOS',
        '223.0': 'SAN MATEO DEL MAR',
        '224.0': 'SAN MATEO ETLATONGO',
        '225.0': 'SAN MATEO NEPANTLA',
        '226.0': 'SAN MATEO PEÑASCO',
        '227.0': 'SAN MATEO PIÑAS',
        '228.0': 'SAN MATEO RÍO HONDO',
        '229.0': 'SAN MATEO SINDIHUI',
        '230.0': 'SAN MATEO TLAPILTEPEC',
        '231.0': 'SAN MELCHOR BETAZA',
        '232.0': 'SAN MIGUEL ACHIUTLA',
        '233.0': 'SAN MIGUEL AHUEHUETITLÁN',
        '234.0': 'SAN MIGUEL ALOÁPAM',
        '235.0': 'SAN MIGUEL AMATITLÁN',
        '236.0': 'SAN MIGUEL AMATLÁN',
        '237.0': 'SAN MIGUEL COATLÁN',
        '238.0': 'SAN MIGUEL CHICAHUA',
        '239.0': 'SAN MIGUEL CHIMALAPA',
        '240.0': 'SAN MIGUEL DEL PUERTO',
        '241.0': 'SAN MIGUEL DEL RÍO',
        '242.0': 'SAN MIGUEL EJUTLA',
        '243.0': 'SAN MIGUEL EL GRANDE',
        '244.0': 'SAN MIGUEL HUAUTLA',
        '245.0': 'SAN MIGUEL MIXTEPEC',
        '246.0': 'SAN MIGUEL PANIXTLAHUACA',
        '247.0': 'SAN MIGUEL PERAS',
        '248.0': 'SAN MIGUEL PIEDRAS',
        '249.0': 'SAN MIGUEL QUETZALTEPEC',
        '250.0': 'SAN MIGUEL SANTA FLOR',
        '251.0': 'SAN MIGUEL SANTA FLOR',
        '252.0': 'SAN MIGUEL SOYALTEPEC',
        '253.0': 'SAN MIGUEL SUCHIXTEPEC',
        '254.0': 'SAN MIGUEL TEQUIXTEPEC',
        '255.0': 'SAN MIGUEL TILQUIÁPAM',
        '256.0': 'SAN MIGUEL TLACAMAMA',
        '257.0': 'SAN MIGUEL TLACOTEPEC',
        '258.0': 'SAN MIGUEL TULANCINGO',
        '259.0': 'SAN MIGUEL YOTAO',
        '260.0': 'SAN NICOLÁS',
        '261.0': 'SAN NICOLÁS HIDALGO',
        '262.0': 'SAN PABLO COATLÁN',
        '263.0': 'SAN PABLO CUATRO VENADOS',
        '264.0': 'SAN PABLO ETLA',
        '265.0': 'SAN PABLO HUITZO',
        '266.0': 'SAN PABLO MACUILTIANGUIS',
        '267.0': 'SAN PABLO TLALCHICHILCO',
        '268.0': 'SAN PABLO TLALIXTLAHUACA',
        '269.0': 'SAN PABLO VILLA DE MITLA',
        '270.0': 'SAN PABLO YAGANIZA',
        '271.0': 'SAN PEDRO AMUZGOS',
        '272.0': 'SAN PEDRO APÓSTOL',
        '273.0': 'SAN PEDRO ATOYAC',
        '274.0': 'SAN PEDRO CAJONOS',
        '275.0': 'SAN PEDRO COXCUMATLAN',
        '276.0': 'SAN PEDRO EL ALTO',
        '277.0': 'SAN PEDRO HUAMELULA',
        '278.0': 'SAN PEDRO HUILOTEPEC',
        '279.0': 'SAN PEDRO IXCATLÁN',
        '280.0': 'SAN PEDRO IXTLAHUACA',
        '281.0': 'SAN PEDRO JALTEPETONGO',
        '282.0': 'SAN PEDRO JICAYÁN',
        '283.0': 'SAN PEDRO JOCOTIPAC',
        '284.0': 'SAN PEDRO JUCHATENGO',
        '285.0': 'SAN PEDRO MARTIR',
        '286.0': 'SAN PEDRO MIXTEPEC',
        '287.0': 'SAN PEDRO MOLINOS',
        '288.0': 'SAN PEDRO NEXICHI',
        '289.0': 'SAN PEDRO OCOTEPEC',
        '290.0': 'SAN PEDRO POCHUTLA',
        '291.0': 'SAN PEDRO QUIATONI',
        '292.0': 'SAN PEDRO SOCHIAPAM',
        '293.0': 'SAN PEDRO TAPANATEPEC',
        '294.0': 'SAN PEDRO TAVICHE',
        '295.0': 'SAN PEDRO TECOLOAPAN',
        '296.0': 'SAN PEDRO TEUTILA',
        '297.0': 'SAN PEDRO TIDAÁ',
        '298.0': 'SAN PEDRO TOPILTEPEC',
        '299.0': 'SAN PEDRO TOTOLÁPAM',
        '300.0': 'SAN PEDRO Y SAN PABLO AYUTLA',
        '301.0': 'SAN PEDRO Y SAN PABLO TEPOSCOLULA',
        '302.0': 'SAN PEDRO Y SAN PABLO TEQUIXTEPEC',
        '303.0': 'SAN PEDRO YANERI',
        '304.0': 'SAN PEDRO YOLOX',
        '305.0': 'SAN PEDRO YUCUXACO',
        '306.0': 'SAN PEDRO YUCUYACHI',
        '307.0': 'SAN PEDRO YUZOYÚ',
        '308.0': 'SAN RAYMUNDO JALPAN',
        '309.0': 'SAN SEBASTIÁN ABASOLO',
        '310.0': 'SAN SEBASTIÁN COATLÁN',
        '311.0': 'SAN SEBASTIÁN IXCAPA',
        '312.0': 'SAN SEBASTIÁN NACALTEPEC',
        '313.0': 'SAN SEBASTIÁN RÍO HONDO',
        '314.0': 'SAN SEBASTIÁN TECOMAXTLAHUACA',
        '315.0': 'SAN SEBASTIÁN TEITIPAC',
        '316.0': 'SAN SEBASTIÁN TUTLA',
        '317.0': 'SAN SIMÓN ALMOLONGAS',
        '318.0': 'SAN SIMÓN ZAHUATLÁN',
        '319.0': 'SANTA ANA',
        '320.0': 'SANTA ANA ATEIXTLAHUACA',
        '321.0': 'SANTA ANA CUAUTEMOC',
        '322.0': 'SANTA ANA DEL VALLE',
        '323.0': 'SANTA ANA TAVELA',
        '324.0': 'SANTA ANA TLAPACOYAN',
        '325.0': 'SANTA ANA YARENI',
        '326.0': 'SANTA ANA ZEGACHE',
        '327.0': 'SANTA CATALINA QUIERI',
        '328.0': 'SANTA CATARINA CUIXTLA',
        '329.0': 'SANTA CATARINA IXTEPEJI',
        '330.0': 'SANTA CATARINA JUQUILA',
        '331.0': 'SANTA CATARINA LACHATAO',
        '332.0': 'SANTA CATARINA LOXICHA',
        '333.0': 'SANTA CATARINA MECHOACÁN',
        '334.0': 'SANTA CATARINA MINAS',
        '335.0': 'SANTA CATARINA QUIANE',
        '336.0': 'SANTA CATARINA TAYATA',
        '337.0': 'SANTA CATARINA TICUA',
        '338.0': 'SANTA CATARINA YOSONOTÚ',
        '339.0': 'SANTA CATARINA ZAPOQUILA',
        '340.0': 'SANTA CRUZ ACATEPEC',
        '341.0': 'SANTA CRUZ AMILPAS',
        '342.0': 'SANTA CRUZ DE BRAVO',
        '343.0': 'SANTA CRUZ ITUNDUJIA',
        '344.0': 'SANTA CRUZ MIXTEPEC',
        '345.0': 'SANTA CRUZ NUNDACO',
        '346.0': 'SANTA CRUZ PAPALUTLA',
        '347.0': 'SANTA CRUZ TACACHE DE MINA',
        '348.0': 'SANTA CRUZ TACAHUA',
        '349.0': 'SANTA CRUZ TAYATA',
        '350.0': 'SANTA CRUZ XITLA',
        '351.0': 'SANTA CRUZ XOXOCOTLÁN',
        '352.0': 'SANTA CRUZ ZENZONTEPEC',
        '353.0': 'SANTA GERTRUDIS',
        '354.0': 'SANTA INÉS DEL MONTE',
        '355.0': 'SANTA INÉS YATZECHE',
        '356.0': 'SANTA LUCÍA DEL CAMINO',
        '357.0': 'SANTA LUCÍA MIAHUATLÁN',
        '358.0': 'SANTA LUCÍA MONTEVERDE',
        '359.0': 'SANTA LUCÍA OCOTLÁN',
        '360.0': 'SANTA MARÍA ALOTEPEC',
        '361.0': 'SANTA MARÍA APAZCO',
        '362.0': 'SANTA MARÍA ATZOMPA',
        '363.0': 'SANTA MARÍA CAMOTLÁN',
        '364.0': 'SANTA MARÍA CHACHOÁPAM',
        '365.0': 'SANTA MARÍA CHILCHOTLA',
        '366.0': 'SANTA MARÍA CHIMALAPA',
        '367.0': 'SANTA MARÍA COLOTEPEC',
        '368.0': 'SANTA MARÍA CORTIJO',
        '369.0': 'SANTA MARÍA COYOTEPEC',
        '370.0': 'SANTA MARÍA DEL ROSARIO',
        '371.0': 'SANTA MARÍA DEL TULE',
        '372.0': 'SANTA MARÍA ECATEPEC',
        '373.0': 'SANTA MARÍA GUELACÉ',
        '374.0': 'SANTA MARÍA GUELAGUISHI',
        '375.0': 'SANTA MARÍA HUATULCO',
        '376.0': 'SANTA MARÍA HUAZOLOTITLÁN',
        '377.0': 'SANTA MARÍA IPALAPA',
        '378.0': 'SANTA MARÍA IXCATLÁN',
        '379.0': 'SANTA MARÍA JACATEPEC',
        '380.0': 'SANTA MARÍA JALAPA DEL MARQUÉS',
        '381.0': 'SANTA MARÍA JALTIANGUIS',
        '382.0': 'SANTA MARÍA LACHIXÍO',
        '383.0': 'SANTA MARÍA MIXTEQUILLA',
        '384.0': 'SANTA MARÍA NATIVITAS',
        '385.0': 'SANTA MARÍA NDUAYACO',
        '386.0': 'SANTA MARÍA OZOLOTEPEC',
        '387.0': 'SANTA MARÍA PAPALO',
        '388.0': 'SANTA MARÍA PEÑOL DE ABAJO',
        '389.0': 'SANTA MARÍA PETAPA',
        '390.0': 'SANTA MARÍA QUIEGOLANI',
        '391.0': 'SANTA MARÍA SINICAHUA',
        '392.0': 'SANTA MARÍA SOLA',
        '393.0': 'SANTA MARÍA TATALTEPEC',
        '394.0': 'SANTA MARÍA TECOLOTLÁN',
        '395.0': 'SANTA MARÍA TEMAXCALAPA',
        '396.0': 'SANTA MARÍA TEMAXCALTEPEC',
        '397.0': 'SANTA MARÍA TEOPOXCO',
        '398.0': 'SANTA MARÍA TEXCATITLÁN',
        '399.0': 'SANTA MARÍA TILTEPEC',
        '400.0': 'SANTA MARÍA TLALIXTAC', 
        '401.0': 'SANTA MARÍA TLALIXTAC',
        '402.0': 'SANTA MARÍA TONAMECA',
        '403.0': 'SANTA MARÍA TOTOLAPILLA',
        '404.0': 'SANTA MARÍA XADANI',
        '405.0': 'SANTA MARÍA YALINA',
        '406.0': 'SANTA MARÍA YAVESÍA',
        '407.0': 'SANTA MARÍA YOLOTEPEC',
        '408.0': 'SANTA MARÍA YOSOYÚA',
        '409.0': 'SANTA MARÍA YUCUHITI',
        '410.0': 'SANTA MARÍA ZANIZA',
        '411.0': 'SANTA MARÍA ZOQUITLÁN',
        '412.0': 'SANTIAGO AMOLTEPEC',
        '413.0': 'SANTIAGO APOALA',
        '414.0': 'SANTIAGO APÓSTOL',
        '415.0': 'SANTIAGO ASTATA',
        '416.0': 'SANTIAGO ATITLÁN',
        '417.0': 'SANTIAGO AYUQUILA',
        '418.0': 'SANTIAGO CACALOXTEPEC',
        '419.0': 'SANTIAGO CAMOTLÁN',
        '420.0': 'SANTIAGO CHAZUMBA',
        '421.0': 'SANTIAGO CHOÁPAM',
        '422.0': 'SANTIAGO COMALTEPEC',
        '423.0': 'SANTIAGO DEL RÍO',
        '424.0': 'SANTIAGO HUAJOLOTITLÁN',
        '425.0': 'SANTIAGO HUAUCLILLA',
        '426.0': 'SANTIAGO IHUITLÁN PLUMAS',
        '427.0': 'SANTIAGO IXCUINTEPEC',
        '428.0': 'SANTIAGO IXTAYUTLA',
        '429.0': 'SANTIAGO JAMILTEPEC',
        '430.0': 'SANTIAGO JOCOTEPEC',
        '431.0': 'SANTIAGO JUXTLAHUACA',
        '432.0': 'SANTIAGO LACHIGUIRI',
        '433.0': 'SANTIAGO LALOPA',
        '434.0': 'SANTIAGO LAOLLAGA',
        '435.0': 'SANTIAGO LAXOPA',
        '436.0': 'SANTIAGO LLANO GRANDE',
        '437.0': 'SANTIAGO MATATLÁN',
        '438.0': 'SANTIAGO MILTEPEC',
        '439.0': 'SANTIAGO MINAS',
        '440.0': 'SANTIAGO NACALTEPEC',
        '441.0': 'SANTIAGO NEJAPILLA',
        '442.0': 'SANTIAGO NILTEPEC',
        '443.0': 'SANTIAGO NUNDICHE',
        '444.0': 'SANTIAGO NUYOÓ',
        '445.0': 'SANTIAGO PINOTEPA NACIONAL',
        '446.0': 'SANTIAGO SUCHILQUITONGO',
        '447.0': 'SANTIAGO TAMAZOLA',
        '448.0': 'SANTIAGO TAPEXTLA',
        '449.0': 'SANTIAGO TENANGO',
        '450.0': 'SANTIAGO TEPETLAPA',
        '451.0': 'SANTIAGO TETEPEC',
        '452.0': 'SANTIAGO TEXCALCINGO',
        '453.0': 'SANTIAGO TEXTITLÁN',
        '454.0': 'SANTIAGO TILANTONGO',
        '455.0': 'SANTIAGO TILOLOYAN',
        '456.0': 'SANTIAGO TLAZOYALTEPEC',
        '457.0': 'SANTIAGO XANICA',
        '458.0': 'SANTIAGO XIACUI',
        '459.0': 'SANTIAGO YAEÉ',
        '460.0': 'SANTIAGO YAITEPEC',
        '461.0': 'SANTIAGO YAVEO',
        '462.0': 'SANTIAGO YOLOMECATL',
        '463.0': 'SANTIAGO YOSONDÚA',
        '464.0': 'SANTIAGO YUCUYACHI',
        '465.0': 'SANTIAGO ZACATEPEC',
        '466.0': 'SANTIAGO ZOOCHILA',
        '467.0': 'SANTO DOMINGO ALBARRADAS',
        '468.0': 'SANTO DOMINGO ARMENTA',
        '469.0': 'SANTO DOMINGO CHIHUITÁN',
        '470.0': 'SANTO DOMINGO DE MORELOS',
        '471.0': 'SANTO DOMINGO INGENIO',
        '472.0': 'SANTO DOMINGO IXCATLÁN',
        '473.0': 'SANTO DOMINGO NANAHUATIPAM',
        '474.0': 'SANTO DOMINGO NUXAA',
        '475.0': 'SANTO DOMINGO OZOLOTEPEC',
        '476.0': 'SANTO DOMINGO PETAPA',
        '477.0': 'SANTO DOMINGO ROAYAGA',
        '478.0': 'SANTO DOMINGO TEHUANTEPEC',
        '479.0': 'SANTO DOMINGO TEOJOMULCO',
        '480.0': 'SANTO DOMINGO TEPUXTEPEC',
        '481.0': 'SANTO DOMINGO TLATAYAPAM',
        '482.0': 'SANTO DOMINGO TOMALTEPEC',
        '483.0': 'SANTO DOMINGO TONALÁ',
        '484.0': 'SANTO DOMINGO TONOLOTEPEC',
        '485.0': 'SANTO DOMINGO XAGACÍA',
        '486.0': 'SANTO DOMINGO YANHUITLÁN',
        '487.0': 'SANTO DOMINGO YODOHONDO',
        '488.0': 'SANTO DOMINGO ZANATEPEC',
        '489.0': 'SANTO TOMÁS JALIETZA',
        '490.0': 'SANTO TOMÁS MAZALTEPEC',
        '491.0': 'SANTO TOMÁS OCOTEPEC',
        '492.0': 'SANTO TOMÁS TAMAZULAPAN',
        '493.0': 'SANTOS REYES NOPALA',
        '494.0': 'SANTOS REYES PAPALO',
        '495.0': 'SANTOS REYES TEPEJILLO',
        '496.0': 'SANTOS REYES YUCUÑÁ',
        '497.0': 'SILACAYOÁPAM',
        '498.0': 'SITIO DE XITLAPEHUA',
        '499.0': 'SOLEDAD ETLA',
        '500.0': 'TAMAZULÁPAM DEL ESPÍRITU SANTO',
        '501.0': 'TANICHE',
        '502.0': 'TEOCOCUILCO DE MARCOS PÉREZ',
        '503.0': 'TEOTITLÁN DE FLORES MAGÓN',
        '504.0': 'TEOTITLÁN DEL VALLE',
        '505.0': 'TILQUIÁPAM',
        '506.0': 'TLACOLULA DE MATAMOROS',
        '507.0': 'TLACOACHISTLAHUACA',
        '508.0': 'TLACOTEPEC PLUMAS',
        '509.0': 'TLALIXTAC DE CABRERA',
        '510.0': 'TOTONTEPEC VILLA DE MORELOS',
        '511.0': 'TRINIDAD ZAACHILA',
        '512.0': 'UNIÓN HIDALGO',
        '513.0': 'VALERIO TRUJANO',
        '514.0': 'VILLA DE CHILAPA DE DÍAZ',
        '515.0': 'VILLA DE ETLA',
        '516.0': 'VILLA DE ZAACHILA',
        '517.0': 'XADANI',
        '518.0': 'YAUTEPEC',
        '519.0': 'ZAPOTITLÁN LAGUNAS',
        '520.0': 'ZAPOTITLÁN PALMAS',
        '521.0': 'ZIMATLÁN DE ÁLVAREZ',
        '522.0': 'SAN PEDRO Y SAN PABLO TEPOSCOLULA',
        '523.0': 'SAN PEDRO Y SAN PABLO TEQUIXTEPEC',
        '524.0': 'SAN RAYMUNDO JALPAN',
        '525.0': 'SAN SEBASTIÁN ABASOLO',
        '526.0': 'SAN SEBASTIÁN COATLAN',
        '527.0': 'SAN SEBASTIÁN IXCAPA',
        '528.0': 'SAN SEBASTIÁN NICANANDUTA',
        '529.0': 'SAN SEBASTIÁN RÍO HONDO',
        '530.0': 'SAN SEBASTIÁN TECOMAXTLAHUACA',
        '531.0': 'SAN SEBASTIÁN TEITIPAC',
        '532.0': 'SAN SEBASTIÁN TUTLA',
        '533.0': 'SAN SIMÓN ALMOLONGAS',
        '534.0': 'SAN SIMÓN ZAHUATLÁN',
        '535.0': 'SAN VICENTE COATLÁN',
        '536.0': 'SAN VICENTE LACHIXÍO',
        '537.0': 'SAN VICENTE NUÑÚ',
        '538.0': 'SANTA ANA',
        '539.0': 'SANTA ANA ATEIXTLAHUACA',
        '540.0': 'SANTA ANA CUAUHTÉMOC',
        '541.0': 'SANTA ANA DEL VALLE',
        '542.0': 'SANTA ANA TAVELA',
        '543.0': 'SANTA ANA TLAPACOYAN',
        '544.0': 'SANTA ANA YARENI',
        '545.0': 'SANTA ANA ZEGACHE',
        '546.0': 'SANTA CATALINA QUIERÍ',
        '547.0': 'SANTA CATARINA CUIXTEPEC',
        '548.0': 'SANTA CATARINA IXTEPEJI',
        '549.0': 'SANTA CATARINA JUQUILA',
        '550.0': 'SANTA CATARINA LACHATAO',
        '551.0': 'SANTA CATARINA LOXICHA',
        '552.0': 'SANTA CATARINA MECHOACÁN',
        '553.0': 'SANTA CATARINA MINAS',
        '554.0': 'SANTA CATARINA QUIOQUITANI',
        '555.0': 'SANTA CATARINA TAYATA',
        '556.0': 'SANTA CATARINA TICUA',
        '557.0': 'SANTA CATARINA YOSONOTÚ',
        '558.0': 'SANTA CATARINA ZAPOQUILA',
        '559.0': 'SANTA CRUZ ACATEPEC',
        '560.0': 'SANTA CRUZ AMILPAS',
        '561.0': 'SANTA CRUZ DE BRAVO',
        '562.0': 'SANTA CRUZ ITUNDUJIA',
        '563.0': 'SANTA CRUZ MIXTEPEC',
        '564.0': 'SANTA CRUZ NUNDACO',
        '565.0': 'SANTA CRUZ PAPALUTLA',
        '566.0': 'SANTA CRUZ TACACHE DE MINA',
        '567.0': 'SANTA CRUZ TACAHUA',
        '568.0': 'SANTA CRUZ TAYATA',
        '569.0': 'SANTA CRUZ XITLA',
        '570.0': 'SANTA CRUZ XOCHITLÁN'
    },

    'PUEBLA': {
        '140.0': 'SANTIAGO MIAHUATLÁN',
        '141.0': 'SANTO TOMÁS HUEYOTLIPAN',
        '142.0': 'SOLTEPEC',
        '143.0': 'TECALI DE HERRERA',
        '144.0': 'TECAMACHALCO',
        '145.0': 'TECOMATLÁN',
        '146.0': 'TEHUACÁN',
        '147.0': 'TEHUITZINGO',
        '148.0': 'TENAMPULCO',
        '149.0': 'TEOPANTLÁN',
        '150.0': 'TEOTLALCO',
        '151.0': 'TEPANCO DE LÓPEZ',
        '152.0': 'TEPANGO DE RODRÍGUEZ',
        '153.0': 'TEPATLAXCO DE HIDALGO',
        '154.0': 'TEPEACA',
        '155.0': 'TEPEMAXALCO',
        '156.0': 'TEPEOJUMA',
        '157.0': 'TEPETZINTLA',
        '158.0': 'TEPEXCO',
        '159.0': 'TEPEXI DE RODRÍGUEZ',
        '160.0': 'TEPEYAHUALCO',
        '161.0': 'TEPEYAHUALCO DE CUAUHTÉMOC',
        '162.0': 'TETELA DE OCAMPO',
        '163.0': 'TETELES DE AVILA CASTILLO',
        '164.0': 'TEZIUTLÁN',
        '165.0': 'TIANGUISTENCO',
        '166.0': 'TILAPA',
        '167.0': 'TLACHICHUCA',
        '168.0': 'TLACOTEPEC DE BENITO JUÁREZ',
        '169.0': 'TLACUILOTEPEC',
        '170.0': 'TLAHUAPAN',
        '171.0': 'TLALTENANGO',
        '172.0': 'TLANEPANTLA',
        '173.0': 'TLAOLA',
        '174.0': 'TLAPACOYA',
        '175.0': 'TLAPANALÁ',
        '176.0': 'TLATLAUQUITEPEC',
        '177.0': 'TLAXCO',
        '178.0': 'TOCHIMILCO',
        '179.0': 'TOCHTEPEC',
        '180.0': 'TOTOLTEPEC DE GUERRERO',
        '181.0': 'TULCINGO',
        '182.0': 'TUZAMAPAN DE GALEANA',
        '183.0': 'TZICATLACOYAN',
        '184.0': 'VENUSTIANO CARRANZA',
        '185.0': 'VICENTE GUERRERO',
        '186.0': 'XAYACATLÁN DE BRAVO',
        '187.0': 'XICOTEPEC',
        '188.0': 'XICOTLÁN',
        '189.0': 'XIUTETELCO',
        '190.0': 'XOCHIAPULCO',
        '191.0': 'XOCHILTEPEC',
        '192.0': 'XOCHITLÁN DE VICENTE SUÁREZ',
        '193.0': 'XOCHITLÁN TODOS SANTOS',
        '194.0': 'YAONÁHUAC',
        '195.0': 'YEHUALTEPEC',
        '196.0': 'ZACAPALA',
        '197.0': 'ZACAPOAXTLA',
        '198.0': 'ZACATLÁN',
        '199.0': 'ZAPOTITLÁN',
        '200.0': 'ZAPOTITLÁN DE MÉNDEZ',
        '201.0': 'ZARAGOZA',
        '202.0': 'ZAUTLA',
        '203.0': 'ZINACATEPEC',
        '204.0': 'ZONGOZOTLA',
        '205.0': 'ZOQUIAPAN',
        '206.0': 'ZOQUITLÁN',
        '207.0': 'ALBINO ZERTUCHE',
        '208.0': 'ATEMPAN',
        '209.0': 'CHIGNAHUAPAN',
        '210.0': 'CHILA DE LA SAL',
        '211.0': 'HUEYAPAN',
        '212.0': 'HUEYTAMALCO',
        '213.0': 'IXCAMILPA DE GUERRERO',
        '214.0': 'IXTEPEC',
        '215.0': 'JOPALA',
        '216.0': 'LIBRES',
        '217.0': 'NICOLÁS BRAVO'
    },

    'QUERÉTARO': {
        '1.0': 'AMEALCO DE BONFIL',
        '2.0': 'PINAL DE AMOLES',
        '3.0': 'ARROYO SECO',
        '4.0': 'CADEREYTA DE MONTES',
        '5.0': 'COLÓN',
        '6.0': 'CORREGIDORA',
        '7.0': 'EZEQUIEL MONTES',
        '8.0': 'HUIMILPAN',
        '9.0': 'JALPAN DE SERRA',
        '10.0': 'LANDA DE MATAMOROS',
        '11.0': 'EL MARQUÉS',
        '12.0': 'PEDRO ESCOBEDO',
        '13.0': 'PEÑAMILLER',
        '14.0': 'QUERÉTARO',
        '15.0': 'SAN JOAQUÍN',
        '16.0': 'SAN JUAN DEL RÍO',
        '17.0': 'TEQUISQUIAPAN',
        '18.0': 'TOLIMÁN'
    },
    'QUINTANA ROO': {
        '1.0': 'BENITO JUÁREZ',
        '2.0': 'COZUMEL',
        '3.0': 'FELIPE CARRILLO PUERTO',
        '4.0': 'ISLA MUJERES',
        '5.0': 'JOSÉ MARÍA MORELOS',
        '6.0': 'LÁZARO CÁRDENAS',
        '7.0': 'OPB (OTHÓN P. BLANCO)',
        '8.0': 'SOLIDARIDAD',
        '9.0': 'TULUM',
        '10.0': 'BACALAR',
        '11.0': 'PUERTO MORELOS'
    },
    'SAN LUIS POTOSÍ': {
        '1.0': 'AHUALULCO',
        '2.0': 'ALAQUINES',
        '3.0': 'AQUISMÓN',
        '4.0': 'ARMADILLO DE LOS INFANTE',
        '5.0': 'AXTLA DE TERRAZAS',
        '6.0': 'CARDENAS',
        '7.0': 'CATORCE',
        '8.0': 'CEDRAL',
        '9.0': 'CERRITOS',
        '10.0': 'CERRO DE SAN PEDRO',
        '11.0': 'CIUDAD DEL MAÍZ',
        '12.0': 'CIUDAD FERNÁNDEZ',
        '13.0': 'TANCANHUITZ',
        '14.0': 'CIUDAD VALLES',
        '15.0': 'COXCATLÁN',
        '16.0': 'CHARCAS',
        '17.0': 'EBANO',
        '18.0': 'GUADALCAZAR',
        '19.0': 'HUEHUETLÁN',
        '20.0': 'LAGUNILLAS',
        '21.0': 'MATEHUALA',
        '22.0': 'MATLAPA',
        '23.0': 'MEXQUITIC DE CARMONA',
        '24.0': 'MOCTEZUMA',
        '25.0': 'RAYÓN',
        '26.0': 'RIOVERDE',
        '27.0': 'SALINAS',
        '28.0': 'SAN ANTONIO',
        '29.0': 'SAN CIRO DE ACOSTA',
        '30.0': 'SAN LUIS POTOSÍ',
        '31.0': 'SAN MARTÍN CHALCHICUAUTLA',
        '32.0': 'SAN NICOLÁS TOLENTINO',
        '33.0': 'SAN VICENTE TANCUAYALAB',
        '34.0': 'SANTA CATARINA',
        '35.0': 'SANTA MARÍA DEL RÍO',
        '36.0': 'SANTO DOMINGO',
        '37.0': 'SOLEDAD DE GRACIANO SÁNCHEZ',
        '38.0': 'TAMASOPO',
        '39.0': 'TAMAZUNCHALE',
        '40.0': 'TAMPACÁN',
        '41.0': 'TAMPAMOLÓN CORONA',
        '42.0': 'TAMUÍN',
        '43.0': 'TANLAJÁS',
        '44.0': 'TANQUIÁN DE ESCOBEDO',
        '45.0': 'TIERRA NUEVA',
        '46.0': 'VANEGAS',
        '47.0': 'VENADO',
        '48.0': 'VILLA DE ARRIAGA',
        '49.0': 'VILLA DE GUADALUPE',
        '50.0': 'VILLA DE LA PAZ',
        '51.0': 'VILLA DE RAMOS',
        '52.0': 'VILLA DE REYES',
        '53.0': 'VILLA HIDALGO',
        '54.0': 'VILLA JUÁREZ',
        '55.0': 'XILITLA',
        '56.0': 'ZARAGOZA'
    },
    'SINALOA': {
        '1.0': 'AHOME',
        '2.0': 'ANGOSTURA',
        '3.0': 'BADIRAGUATO',
        '4.0': 'CONCORDIA',
        '5.0': 'COSALÁ',
        '6.0': 'CULIACÁN',
        '7.0': 'CHOIX',
        '8.0': 'ELOTA',
        '9.0': 'ESCUINAPA',
        '10.0': 'FUERTE',
        '11.0': 'GUASAVE',
        '12.0': 'MAZATLÁN',
        '13.0': 'MOCORITO',
        '14.0': 'NAVOLATO',
        '15.0': 'ROSARIO',
        '16.0': 'SALVADOR ALVARADO',
        '17.0': 'SAN IGNACIO',
        '18.0': 'SINALOA'
    },
    'SONORA': {
        '1.0': 'ABÁSOLO',
        '2.0': 'ACONCHI',
        '3.0': 'AGUA PRIETA',
        '4.0': 'ÁLAMOS',
        '5.0': 'ALTAR',
        '6.0': 'ARIVECHI',
        '7.0': 'ARIZPE',
        '8.0': 'ATOYAC',
        '9.0': 'BACOACHI',
        '10.0': 'BACUM',
        '11.0': 'BANÁMICHI',
        '12.0': 'BAVIÁCORA',
        '13.0': 'BAVISPE',
        '14.0': 'BENJAMÍN HILL',
        '15.0': 'CABORCA',
        '16.0': 'CAJEME',
        '17.0': 'CANANEA',
        '18.0': 'CARBÓ',
        '19.0': 'LA COLORADA',
        '20.0': 'CUCURPE',
        '21.0': 'CUMPAS',
        '22.0': 'DIVISADEROS',
        '23.0': 'EMPALME',
        '24.0': 'ETCHOJOA',
        '25.0': 'FRONTERAS',
        '26.0': 'GRANADOS',
        '27.0': 'GUAYMAS',
        '28.0': 'HERMOSILLO',
        '29.0': 'HUACHINERA',
        '30.0': 'HUÁSABAS',
        '31.0': 'HUATABAMPO',
        '32.0': 'HUEPAC',
        '33.0': 'IMURIS',
        '34.0': 'MAGDALENA',
        '35.0': 'MAZATÁN',
        '36.0': 'MOCTEZUMA',
        '37.0': 'NACO',
        '38.0': 'NACORI CHICO',
        '39.0': 'NACORI GRANDE',
        '40.0': 'NAVOJOA',
        '41.0': 'NOGALES',
        '42.0': 'ONAVAS',
        '43.0': 'OPODEPE',
        '44.0': 'OQUITOA',
        '45.0': 'PITIQUITO',
        '46.0': 'PUERTO PEÑASCO',
        '47.0': 'QUIRIEGO',
        '48.0': 'RAYÓN',
        '49.0': 'ROSARIO',
        '50.0': 'SAHUARIPA',
        '51.0': 'SAN FELIPE DE JESÚS',
        '52.0': 'SAN JAVIER',
        '53.0': 'SAN LUIS RÍO COLORADO',
        '54.0': 'SAN MIGUEL DE HORCASITAS',
        '55.0': 'SAN PEDRO DE LA CUEVA',
        '56.0': 'SANTA ANA',
        '57.0': 'SANTA CRUZ',
        '58.0': 'SÁRIC',
        '59.0': 'SOYOPA',
        '60.0': 'SUAQUI GRANDE',
        '61.0': 'TEPACHE',
        '62.0': 'TRINCHERAS',
        '63.0': 'TUBUTAMA',
        '64.0': 'URES',
        '65.0': 'VILLA HIDALGO',
        '66.0': 'VILLA PESQUEIRA',
        '67.0': 'YÉCORA',
        '68.0': 'GENERAL PLUTARCO ELÍAS CALLES',
        '69.0': 'SAN IGNACIO RÍO MUERTO',
        '70.0': 'BACADÉHUACHI',
        '71.0': 'BAVISPE',
        '72.0': 'SAN PEDRO DE LA CUEVA'
    },
    'TABASCO': {
        '1.0': 'BALANCÁN',
        '2.0': 'CÁRDENAS',
        '3.0': 'CENTLA',
        '4.0': 'CENTRO',
        '5.0': 'COMALCALCO',
        '6.0': 'CUNDUACÁN',
        '7.0': 'EMILIANO ZAPATA',
        '8.0': 'HUIMANGUILLO',
        '9.0': 'JALAPA',
        '10.0': 'JALPA DE MÉNDEZ',
        '11.0': 'JONUTA',
        '12.0': 'MACUSPANA',
        '13.0': 'NACAJUCA',
        '14.0': 'PARAÍSO',
        '15.0': 'TACOTALPA',
        '16.0': 'TEAPA',
        '17.0': 'TENOSIQUE'
    },
    'TAMAULIPAS': {
        '1.0': 'ABASOLO',
        '2.0': 'ALDAMA',
        '3.0': 'ALTAMIRA',
        '4.0': 'ANTIGUO MORELOS',
        '5.0': 'BURGOS',
        '6.0': 'BUSCARELLO',
        '7.0': 'CAMARGO',
        '8.0': 'CASAS',
        '9.0': 'CIUDAD MADERO',
        '10.0': 'CRUILLAS',
        '11.0': 'GÓMEZ FARÍAS',
        '12.0': 'GONZÁLEZ',
        '13.0': 'GÜÉMEZ',
        '14.0': 'GUERRERO',
        '15.0': 'GUSTAVO DÍAZ ORDAZ',
        '16.0': 'HIDALGO',
        '17.0': 'JAUMAVE',
        '18.0': 'JIMÉNEZ',
        '19.0': 'LLERA',
        '20.0': 'MAINERO',
        '21.0': 'EL MANTE',
        '22.0': 'MATAMOROS',
        '23.0': 'MENDEZ',
        '24.0': 'MIER',
        '25.0': 'MIGUEL ALEMÁN',
        '26.0': 'MIQUIHUANA',
        '27.0': 'NUEVO LAREDO',
        '28.0': 'NUEVO MORELOS',
        '29.0': 'OCAMPO',
        '30.0': 'PADILLA',
        '31.0': 'PALMILLAS',
        '32.0': 'REYNOSA',
        '33.0': 'RÍO BRAVO',
        '34.0': 'SAN CARLOS',
        '35.0': 'SAN FERNANDO',
        '36.0': 'SAN NICOLÁS',
        '37.0': 'SOTO LA MARINA',
        '38.0': 'TAMPICO',
        '39.0': 'TULA',
        '40.0': 'VALLE HERMOSO',
        '41.0': 'VICTORIA',
        '42.0': 'VILLAGRÁN',
        '43.0': 'XICOTÉNCATL'
    },
    'TLAXCALA': {
        '1.0': 'ACUAMANALA DE MIGUEL HIDALGO',
        '2.0': 'AMAXAC DE GUERRERO',
        '3.0': 'APETATITLÁN DE ANTONIO CARVAJAL',
        '4.0': 'APIZACO',
        '5.0': 'ATLANGATEPEC',
        '6.0': 'BENITO JUÁREZ',
        '7.0': 'CALPULALPAN',
        '8.0': 'CHIAUTEMPAN',
        '9.0': 'CONTLA DE JUAN CUAMATZI',
        '10.0': 'CUAPIAXTLA',
        '11.0': 'CUAXOMULCO',
        '12.0': 'EL CARMEN TEQUEXQUITLA',
        '13.0': 'EMILIANO ZAPATA',
        '14.0': 'ESPAÑITA',
        '15.0': 'HUAMANTLA',
        '16.0': 'HUEYOTLIPAN',
        '17.0': 'IXTACUIXTLA DE MARIANO MATAMOROS',
        '18.0': 'IXTENCO',
        '19.0': 'LA MAGDALENA TLALTELULCO',
        '20.0': 'LÁZARO CÁRDENAS',
        '21.0': 'MAZATECOCHCO DE JOSÉ MARÍA MORELOS',
        '22.0': 'MIXCOAC',
        '23.0': 'MUÑOZ DE DOMÍNGUEZ',
        '24.0': 'NANACAMILPA DE MARIANO ARISTA',
        '25.0': 'NATIVITAS',
        '26.0': 'PANOTLA',
        '27.0': 'PAPALOTLA DE XICOHTÉNCATL',
        '28.0': 'SAN DAMIÁN TEXÓLOC',
        '29.0': 'SAN FRANCISCO TETLANOHCAN',
        '30.0': 'SAN JERÓNIMO ZACUALPAN',
        '31.0': 'SAN JOSÉ TEACALCO',
        '32.0': 'SAN JUAN HUACTZINCO',
        '33.0': 'SAN LORENZO AXOCOMANITLA',
        '34.0': 'SAN LUCAS TECOPILCO',
        '35.0': 'SAN PABLO DEL MONTE',
        '36.0': 'SANCTÓRUM DE LÁZARO CÁRDENAS',
        '37.0': 'SANTA ANA NOPALUCAN',
        '38.0': 'SANTA APOLONIA TEACALCO',
        '39.0': 'SANTA CATARINA AYOMETLA',
        '40.0': 'SANTA CRUZ QUILEHTLA',
        '41.0': 'SANTA CRUZ TLAXCALA',
        '42.0': 'SANTA ISABEL XILOXOXTLA',
        '43.0': 'TENANCINGO',
        '44.0': 'TEOLOCHOLCO',
        '45.0': 'TEPEYANCO',
        '46.0': 'TERRÉNATE',
        '47.0': 'TETLA DE LA SOLIDARIDAD',
        '48.0': 'TETLATLAHUCA',
        '49.0': 'TLAXCALA',
        '50.0': 'TLAXCO',
        '51.0': 'TOCATLÁN',
        '52.0': 'TOTOLAC',
        '53.0': 'TZOMPANTEPEC',
        '54.0': 'XALOZTOC',
        '55.0': 'XALTÓCAN',
        '56.0': 'XOCHITEOTLA',
        '57.0': 'YAUHQUEMEHCAN',
        '58.0': 'ZACATELCO',
        '59.0': 'ZILTALTEPEC DE TRINIDAD SÁNCHEZ SANTOS',
        '60.0': 'ZITLALTEPEC DE TRINIDAD SÁNCHEZ SANTOS'
    },
    'VERACRUZ': {
        '1.0': 'ACAJETE',
        '2.0': 'ACATLÁN',
        '3.0': 'ACAYUCAN',
        '4.0': 'ACTOPAN',
        '5.0': 'ACULA',
        '6.0': 'ACULTZINGO',
        '7.0': 'AGUA DULCE',
        '8.0': 'ALPATLÁHUAC',
        '9.0': 'ALTO LUCERO DE GUTIÉRREZ BARRIOS',
        '10.0': 'ALTOTONGA',
        '11.0': 'ALVARADO',
        '12.0': 'AMATITLÁN',
        '13.0': 'AMATLÁN DE LOS REYES',
        '14.0': 'ANGEL R. CABADA',
        '15.0': 'APAZAPAN',
        '16.0': 'AQUILA',
        '17.0': 'ASTACINGA',
        '18.0': 'ATLAHUILCO',
        '19.0': 'ATOYAC',
        '20.0': 'ATZACAN',
        '21.0': 'ATZALAN',
        '22.0': 'AYAHUALULCO',
        '23.0': 'BANDERILLA',
        '24.0': 'BENITO JUÁREZ',
        '25.0': 'BOCA DEL RÍO',
        '26.0': 'CALCAHUALCO',
        '27.0': 'CAMARÓN DE TEJEDA',
        '28.0': 'CAMPO GRANDE',
        '29.0': 'CARLOS A. CARRILLO',
        '30.0': 'CARRILLO PUERTO',
        '31.0': 'CATEMACO',
        '32.0': 'CAZONES DE HERRERA',
        '33.0': 'CERRO AZUL',
        '34.0': 'CHACALTIANGUIS',
        '35.0': 'CHALMA',
        '36.0': 'CHICONAMEL',
        '37.0': 'CHICONQUIACO',
        '38.0': 'CHICONTEPEC',
        '39.0': 'CHINAMECA',
        '40.0': 'CHINAMPA DE GOROSTIZA',
        '41.0': 'CHOCAMÁN',
        '42.0': 'CHONTLA',
        '43.0': 'CHUMATLÁN',
        '44.0': 'CITLALTÉPETL',
        '45.0': 'COACOATZINTLA',
        '46.0': 'COAHUITLÁN',
        '47.0': 'COATEPEC',
        '48.0': 'COATZACOALCOS',
        '49.0': 'COATZINTLA',
        '50.0': 'COETZALA',
        '51.0': 'COLIPA',
        '52.0': 'COMAPA',
        '53.0': 'CÓRDOBA',
        '54.0': 'COSAMALOAPAN DE CARPIO',
        '55.0': 'COSAUTLÁN DE CARVAJAL',
        '56.0': 'COSCOMATEPEC',
        '57.0': 'COSOLEACAQUE',
        '58.0': 'COTAXTLA',
        '59.0': 'COXQUIHUI',
        '60.0': 'COYUTLA',
        '61.0': 'CUICHAPA',
        '62.0': 'CUITLÁHUAC',
        '63.0': 'EL HIGO',
        '64.0': 'EMILIANO ZAPATA',
        '65.0': 'ESPINAL',
        '66.0': 'FILOMENO MATA',
        '67.0': 'FORTÍN',
        '68.0': 'GUTIÉRREZ ZAMORA',
        '69.0': 'HIDALGOTITLÁN',
        '70.0': 'HUATUSCO',
        '71.0': 'HUAYACOCOTLA',
        '72.0': 'HUEYAPAN DE OCAMPO',
        '73.0': 'HUILOAPAN DE CUAUHTÉMOC',
        '74.0': 'IGNACIO DE LA LLAVE',
        '75.0': 'ILAMATLÁN',
        '76.0': 'ISLA',
        '77.0': 'IXCATEPEC',
        '78.0': 'IXHUACÁN DE LOS REYES',
        '79.0': 'IXHUATLÁN DEL CAFÉ',
        '80.0': 'IXHUATLÁN DEL SURESTE',
        '81.0': 'IXHUATLÁN DE MADERO',
        '82.0': 'IXMATLAHUACAN',
        '83.0': 'IXTACZOQUITLÁN',
        '84.0': 'JALACINGO',
        '85.0': 'JALCOMULCO',
        '86.0': 'JÁLTIPAN',
        '87.0': 'JAMAPA',
        '88.0': 'JESÚS CARRANZA',
        '89.0': 'JILOTEPEC',
        '90.0': 'JOSÉ AZUETA',
        '91.0': 'JUAN RODRÍGUEZ CLARA',
        '92.0': 'JUCHIQUE DE FERRER',
        '93.0': 'LANDERO Y COSS',
        '94.0': 'LAS CHOAPAS',
        '95.0': 'LAS MINAS',
        '96.0': 'LAS VIGAS DE RAMÍREZ',
        '97.0': 'LOS REYES',
        '98.0': 'MAGDALENA',
        '99.0': 'MALTRATA',
        '100.0': 'MANLIO FABIO ALTAMIRANO',
        '101.0': 'MARIANO ESCOBEDO',
        '102.0': 'MARTÍNEZ DE LA TORRE',
        '103.0': 'MECATLÁN',
        '104.0': 'MECAYAPAN',
        '105.0': 'MEDELLÍN',
        '106.0': 'MIAHUATLÁN',
        '107.0': 'MINATITLÁN',
        '108.0': 'MIXTLA DE ALTAMIRANO',
        '109.0': 'NAOLINCO',
        '110.0': 'NARANJAL',
        '111.0': 'NAUTLA',
        '112.0': 'NOGALES',
        '113.0': 'OLUTA',
        '114.0': 'ORIZABA',
        '115.0': 'OTEAPAN',
        '116.0': 'OZULUAMA DE MASCAREÑAS',
        '117.0': 'PAJAPAN',
        '118.0': 'PANUCO',
        '119.0': 'PAPANTLA',
        '120.0': 'PASO DEL MACHO',
        '121.0': 'PASO DE OVEJAS',
        '122.0': 'PLATÓN SÁNCHEZ',
        '123.0': 'PLAYA VICENTE',
        '124.0': 'POZA RICA DE HIDALGO',
        '125.0': 'PUEBLO VIEJO',
        '126.0': 'PUXTLÁN',
        '127.0': 'RAFAEL DELGADO',
        '128.0': 'RAFAEL LUCIO',
        '129.0': 'SALTABARRANCA',
        '130.0': 'SAN ANDRÉS TUXTLA',
        '131.0': 'SAN JUAN EVANGELISTA',
        '132.0': 'SAN RAFAEL',
        '133.0': 'SANTIAGO TUXTLA',
        '134.0': 'SAYULA DE ALEMÁN',
        '135.0': 'SOCHIAPA',
        '136.0': 'SOLEDAD ATZOMPA',
        '137.0': 'TAMALÍN',
        '138.0': 'TAMIAHUA',
        '139.0': 'TAMPICO ALTO',
        '140.0': 'TANTOYUCA',
        '141.0': 'TATAHUICAPAN DE JUÁREZ',
        '142.0': 'TATATILA',
        '143.0': 'TECOLUTLA',
        '144.0': 'TEHUIPANGO',
        '145.0': 'TEMAPACHE',
        '146.0': 'TENAMPA',
        '147.0': 'TENOCHTITLÁN',
        '148.0': 'TODOS LOS DEMÁS (HASTA 212)',
        '148.0': 'SAN ANDRÉS TENEJAPAN',
        '149.0': 'SAN ANDRÉS TUXTLA',
        '150.0': 'SAN JUAN EVANGELISTA',
        '151.0': 'SANTIAGO SOCHIAPAN',
        '152.0': 'SANTIAGO TUXTLA',
        '153.0': 'SAYULA DE ALEMÁN',
        '154.0': 'SOCHIAPA',
        '155.0': 'SOLEDAD ATZOMPA',
        '156.0': 'SOLEDAD DE DOBLADO',
        '157.0': 'SOTEAPAN',
        '158.0': 'TAMALÍN',
        '159.0': 'TAMIAHUA',
        '160.0': 'TAMPICO ALTO',
        '161.0': 'TANCOCO',
        '162.0': 'TANTIMA',
        '163.0': 'TANTOYUCA',
        '164.0': 'TATATILA',
        '165.0': 'TECOLUTLA',
        '166.0': 'TEHUIPANGO',
        '167.0': 'TEMAPACHE',
        '168.0': 'TEMOAYO',
        '169.0': 'TENAMPA',
        '170.0': 'TENOCHTITLÁN',
        '171.0': 'TEOCELO',
        '172.0': 'TEPATLAXCO',
        '173.0': 'TEPETLÁN',
        '174.0': 'TEPETZINTLA',
        '175.0': 'TEQUILA',
        '176.0': 'TEXCATEPEC',
        '177.0': 'TEXHUACÁN',
        '178.0': 'TEXISTEPEC',
        '179.0': 'TEZONAPA',
        '180.0': 'TIHUATLÁN',
        '181.0': 'TLACOJALPAN',
        '182.0': 'TLACOLULAN',
        '183.0': 'TLACOTALPAN',
        '184.0': 'TLACOTEPEC DE MEJÍA',
        '185.0': 'TLALIXCOYAN',
        '186.0': 'TLALNELHUAYOCAN',
        '187.0': 'TLAPACOYAN',
        '188.0': 'TLILAPAN',
        '189.0': 'TOMATLÁN',
        '190.0': 'TONAYÁN',
        '191.0': 'TOTUTLA',
        '192.0': 'TUXPAN',
        '193.0': 'TUXTILLA',
        '194.0': 'URSULO GALVÁN',
        '195.0': 'UXPANAPA',
        '196.0': 'VEGA DE ALATORRE',
        '197.0': 'VERACRUZ',
        '198.0': 'VILLA ALDAMA',
        '199.0': 'XALAPA',
        '200.0': 'XICO',
        '201.0': 'XOXOCOTLA',
        '202.0': 'YANGA',
        '203.0': 'YECUATLA',
        '204.0': 'ZACUALPAN',
        '205.0': 'ZARAGOZA',
        '206.0': 'ZENTLA',
        '207.0': 'ZONGOLICA',
        '208.0': 'ZONTECOMATLÁN DE LÓPEZ Y FUENTES',
        '209.0': 'ZOZOCOLCO DE HIDALGO',
        '210.0': 'AGUA DULCE',
        '211.0': 'EL HIGO',
        '212.0': 'NANCHITAL DE LÁZARO CÁRDENAS DEL RÍO'
    },
    'YUCATÁN': {
        '1.0': 'ABALÁ',
        '2.0': 'ACANCEH',
        '3.0': 'AKIL',
        '4.0': 'BACA',
        '5.0': 'BOKOBÁ',
        '6.0': 'BUCTZOTZ',
        '7.0': 'CACALCHÉN',
        '8.0': 'CALOTMUL',
        '9.0': 'CANSAHCAB',
        '10.0': 'CANTAMAYEC',
        '11.0': 'CELESTÚN',
        '12.0': 'CENOTILLO',
        '13.0': 'CONKAL',
        '14.0': 'CUNCUNUL',
        '15.0': 'CUZAMÁ',
        '16.0': 'CHACSINKÍN',
        '17.0': 'CHANKOM',
        '18.0': 'CHAPAB',
        '19.0': 'CHEMAX',
        '20.0': 'CHICXULUB PUEBLO',
        '21.0': 'CHICHIMILÁ',
        '22.0': 'CHIKINDZONOT',
        '23.0': 'CHUMAYEL',
        '24.0': 'DZÁN',
        '25.0': 'DZEMUL',
        '26.0': 'DZIDZANTÚN',
        '27.0': 'DZILAM DE BRAVO',
        '28.0': 'DZILAM GONZÁLEZ',
        '29.0': 'DZITÁS',
        '30.0': 'DZONCAUICH',
        '31.0': 'ESPITA',
        '32.0': 'HALACHÓ',
        '33.0': 'HOCABÁ',
        '34.0': 'HOCTÚN',
        '35.0': 'HOMÚN',
        '36.0': 'HUHÍ',
        '37.0': 'HUNUCMÁ',
        '38.0': 'IXIL',
        '39.0': 'IZAMAL',
        '40.0': 'KANASÍN',
        '41.0': 'KANTUNIL',
        '42.0': 'KAUA',
        '43.0': 'KINCHIL',
        '44.0': 'KOPOMÁ',
        '45.0': 'MAMA',
        '46.0': 'MANÍ',
        '47.0': 'MAXCANÚ',
        '48.0': 'MAYAPÁN',
        '49.0': 'MÉRIDA',
        '50.0': 'MOCOCHÁ',
        '51.0': 'MOTUL',
        '52.0': 'MUNA',
        '53.0': 'MUXUPIP',
        '54.0': 'OPICHÉN',
        '55.0': 'OXKUTZCAB',
        '56.0': 'PANABÁ',
        '57.0': 'PETO',
        '58.0': 'PROGRESO',
        '59.0': 'QUINTANA ROO',
        '60.0': 'RÍO LAGARTOS',
        '61.0': 'SACALUM',
        '62.0': 'SAMAHIL',
        '63.0': 'SANAHCAT',
        '64.0': 'SAN FELIPE',
        '65.0': 'SANTA ELENA',
        '66.0': 'SEYÉ',
        '67.0': 'SINANCHÉ',
        '68.0': 'SOTUTA',
        '69.0': 'SUCILÁ',
        '70.0': 'SUDZAL',
        '71.0': 'SUMA',
        '72.0': 'TAHDZIÚ',
        '73.0': 'TAHMEK',
        '74.0': 'TEABO',
        '75.0': 'TECOH',
        '76.0': 'TEKAL DE VENEGAS',
        '77.0': 'TEKANTÓ',
        '78.0': 'TEKAX',
        '79.0': 'TEKIT',
        '80.0': 'TEKOM',
        '81.0': 'TELCHAC PUEBLO',
        '82.0': 'TELCHAC PUERTO',
        '83.0': 'TEMAX',
        '84.0': 'TEMOZÓN',
        '85.0': 'TETIZ',
        '86.0': 'TEYA',
        '87.0': 'TICUL',
        '88.0': 'TIMUCUY',
        '89.0': 'TINUM',
        '90.0': 'TIXCACALCUPUL',
        '91.0': 'TIXKOKOB',
        '92.0': 'TIXMEHUAC',
        '93.0': 'TIXPÉHUAL',
        '94.0': 'TIZIMÍN',
        '95.0': 'TUNKÁS',
        '96.0': 'TZUCACAB',
        '97.0': 'UAYMA',
        '98.0': 'UCÚ',
        '99.0': 'UMÁN',
        '100.0': 'VALLADOLID',
        '101.0': 'XOCCHEL',
        '102.0': 'YAXCABÁ',
        '103.0': 'YAXKUKUL',
        '104.0': 'YOBAÍN',
        '105.0': 'SAN CATHERINE',
        '106.0': 'SAN PEDRO'
    },
    'ZACATECAS': {
        '1.0': 'APOZOL',
        '2.0': 'APULCO',
        '3.0': 'ATOLINGA',
        '4.0': 'BENITO JUÁREZ',
        '5.0': 'CALERA',
        '6.0': 'CAÑITAS DE FELIPE PESCADOR',
        '7.0': 'CONCEPCIÓN DEL ORO',
        '8.0': 'CUAUHTÉMOC',
        '9.0': 'CHALCHIHUITES',
        '10.0': 'FRESNILLO',
        '11.0': 'TRINIDAD GARCÍA DE LA CADENA',
        '12.0': 'GENARO CODINA',
        '13.0': 'GENERAL ENRIQUE ESTRADA',
        '14.0': 'GENERAL FRANCISCO R. MURGUÍA',
        '15.0': 'EL PLATEADO DE JOAQUÍN AMARO',
        '16.0': 'GENERAL PÁNFILO NATERA',
        '17.0': 'GUADALUPE',
        '18.0': 'HUANUSCO',
        '19.0': 'JALPA',
        '20.0': 'JEREZ',
        '21.0': 'JIMÉNEZ DEL TEUL',
        '22.0': 'JUAN ALDAMA',
        '23.0': 'JUCHIPILA',
        '24.0': 'LORETO',
        '25.0': 'LUIS MOYA',
        '26.0': 'MAZAPIL',
        '27.0': 'MELCHOR OCAMPO',
        '28.0': 'MEZQUITAL DEL ORO',
        '29.0': 'MIGUEL AUZA',
        '30.0': 'MOMAX',
        '31.0': 'MONTE ESCOBEDO',
        '32.0': 'MORELOS',
        '33.0': 'MOYAHUA DE ESTRADA',
        '34.0': 'NOCHISTLÁN DE MEJÍA',
        '35.0': 'NORIA DE ÁNGELES',
        '36.0': 'OJOCALIENTE',
        '37.0': 'PÁNUCO',
        '38.0': 'PINOS',
        '39.0': 'RÍO GRANDE',
        '40.0': 'SAÍN ALTO',
        '41.0': 'EL SALVADOR',
        '42.0': 'SOMBRERETE',
        '43.0': 'SUSTICACÁN',
        '44.0': 'TABASCO',
        '45.0': 'TEPETONGO',
        '46.0': 'TEÚL DE GONZÁLEZ ORTEGA',
        '47.0': 'TLALTENANGO DE SÁNCHEZ ROMÁN',
        '48.0': 'VALPARAÍSO',
        '49.0': 'VETAGRANDE',
        '50.0': 'VILLA DE COS',
        '51.0': 'VILLA GARCÍA',
        '52.0': 'VILLA GONZÁLEZ ORTEGA',
        '53.0': 'VILLA HIDALGO',
        '54.0': 'VILLANUEVA',
        '55.0': 'ZACATECAS',
        '56.0': 'TRANCOSO',
        '57.0': 'SANTA MARÍA DE LA PAZ',
        '58.0': 'LUIS MOYA'
    }

}
